//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef COMMTRACKINGOBJECTS_COMMDETECTEDMARKER_CORE_H_
#define COMMTRACKINGOBJECTS_COMMDETECTEDMARKER_CORE_H_

#include "CommTrackingObjects/CommDetectedMarkerData.hh"
#include "CommBasicObjects/CommPose3d.hh"

#include <iostream>
#include <string>
#include <list>

namespace CommTrackingObjects {
	
class CommDetectedMarkerCore {
protected:
	// data structure
	CommTrackingObjectsIDL::CommDetectedMarker idl_CommDetectedMarker;
	
public:
	// give a publicly accessible type-name for the template parameter IDL
	typedef CommTrackingObjectsIDL::CommDetectedMarker DATATYPE;
	
	#ifdef ENABLE_HASH
		static size_t generateDataHash(const DATATYPE &);
	#endif
	
	static const char* getCompiledHash();
	static void getAllHashValues(std::list<std::string> &hashes);
	static void checkAllHashValues(std::list<std::string> &hashes);
	
	// default constructors
	CommDetectedMarkerCore();
	CommDetectedMarkerCore(const DATATYPE &data);
	// default destructor
	virtual ~CommDetectedMarkerCore();
	
	const DATATYPE& get() const { return idl_CommDetectedMarker; }
	operator const DATATYPE&() const { return idl_CommDetectedMarker; }
	DATATYPE& set() { return idl_CommDetectedMarker; }

	static inline std::string identifier(void) { return "CommTrackingObjects::CommDetectedMarker"; }
	
	// helper method to easily implement output stream in derived classes
	void to_ostream(std::ostream &os = std::cout) const;
	
	// convert to xml stream
	void to_xml(std::ostream &os, const std::string &indent = "") const;
	
	// restore from xml stream
	void from_xml(std::istream &is);
	
	// User Interface
	
	// getter and setter for element Id
	inline unsigned int getId() const { return idl_CommDetectedMarker.id; }
	inline CommDetectedMarkerCore& setId(const unsigned int &id) { idl_CommDetectedMarker.id = id; return *this; }
	
	// getter and setter for element Pose
	inline CommBasicObjects::CommPose3d getPose() const { return CommBasicObjects::CommPose3d(idl_CommDetectedMarker.pose); }
	inline CommDetectedMarkerCore& setPose(const CommBasicObjects::CommPose3d &pose) { idl_CommDetectedMarker.pose = pose; return *this; }
};

} /* namespace CommTrackingObjects */
#endif /* COMMTRACKINGOBJECTS_COMMDETECTEDMARKER_CORE_H_ */
