//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef COMMTRACKINGOBJECTS_COMMPERSONLOSTEVENTRESULT_ACE_H_
#define COMMTRACKINGOBJECTS_COMMPERSONLOSTEVENTRESULT_ACE_H_

#include "CommTrackingObjects/CommPersonLostEventResult.hh"

#include <ace/CDR_Stream.h>

// serialization operator for DataStructure CommPersonLostEventResult
ACE_CDR::Boolean operator<<(ACE_OutputCDR &cdr, const CommTrackingObjectsIDL::CommPersonLostEventResult &data);

// de-serialization operator for DataStructure CommPersonLostEventResult
ACE_CDR::Boolean operator>>(ACE_InputCDR &cdr, CommTrackingObjectsIDL::CommPersonLostEventResult &data);

// serialization operator for CommunicationObject CommPersonLostEventResult
ACE_CDR::Boolean operator<<(ACE_OutputCDR &cdr, const CommTrackingObjects::CommPersonLostEventResult &obj);

// de-serialization operator for CommunicationObject CommPersonLostEventResult
ACE_CDR::Boolean operator>>(ACE_InputCDR &cdr, CommTrackingObjects::CommPersonLostEventResult &obj);

#endif /* COMMTRACKINGOBJECTS_COMMPERSONLOSTEVENTRESULT_ACE_H_ */
