//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef COMMTRACKINGOBJECTS_COMMPERSONID_CORE_H_
#define COMMTRACKINGOBJECTS_COMMPERSONID_CORE_H_

#include "CommTrackingObjects/CommPersonIdData.hh"

#include <iostream>
#include <string>
#include <list>

namespace CommTrackingObjects {
	
class CommPersonIdCore {
protected:
	// data structure
	CommTrackingObjectsIDL::CommPersonId idl_CommPersonId;
	
public:
	// give a publicly accessible type-name for the template parameter IDL
	typedef CommTrackingObjectsIDL::CommPersonId DATATYPE;
	
	#ifdef ENABLE_HASH
		static size_t generateDataHash(const DATATYPE &);
	#endif
	
	static const char* getCompiledHash();
	static void getAllHashValues(std::list<std::string> &hashes);
	static void checkAllHashValues(std::list<std::string> &hashes);
	
	// default constructors
	CommPersonIdCore();
	CommPersonIdCore(const DATATYPE &data);
	// default destructor
	virtual ~CommPersonIdCore();
	
	const DATATYPE& get() const { return idl_CommPersonId; }
	operator const DATATYPE&() const { return idl_CommPersonId; }
	DATATYPE& set() { return idl_CommPersonId; }

	static inline std::string identifier(void) { return "CommTrackingObjects::CommPersonId"; }
	
	// helper method to easily implement output stream in derived classes
	void to_ostream(std::ostream &os = std::cout) const;
	
	// convert to xml stream
	void to_xml(std::ostream &os, const std::string &indent = "") const;
	
	// restore from xml stream
	void from_xml(std::istream &is);
	
	// User Interface
	
	// getter and setter for element Id
	inline unsigned int getId() const { return idl_CommPersonId.id; }
	inline CommPersonIdCore& setId(const unsigned int &id) { idl_CommPersonId.id = id; return *this; }
};

} /* namespace CommTrackingObjects */
#endif /* COMMTRACKINGOBJECTS_COMMPERSONID_CORE_H_ */
