//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef COMMTRACKINGOBJECTS_COMMTRACKINGGOAL_DATA_H_
#define COMMTRACKINGOBJECTS_COMMTRACKINGGOAL_DATA_H_

#include "CommTrackingObjects/enumTrackingGoalTypeData.hh"

#include <vector>

namespace CommTrackingObjectsIDL 
{
	typedef std::vector<double> CommTrackingGoal_cov_type;
	struct CommTrackingGoal
	{
		CommTrackingObjectsIDL::TrackingGoalType trackingType;
		double angle;
		double distance;
		double x;
		double y;
		bool isValid;
		CommTrackingGoal_cov_type cov;
		unsigned long int goalCount;
  	};
};

#endif /* COMMTRACKINGOBJECTS_COMMTRACKINGGOAL_DATA_H_ */
