//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#include "CommTrackingObjects/CommDetectedMarkerEventParameterACE.hh"
#include <ace/SString.h>

// serialization operator for element CommDetectedMarkerEventParameter
ACE_CDR::Boolean operator<<(ACE_OutputCDR &cdr, const CommTrackingObjectsIDL::CommDetectedMarkerEventParameter &data)
{
	ACE_CDR::Boolean good_bit = true;
	// serialize list-element tag_ids
	good_bit = good_bit && cdr << ACE_Utils::truncate_cast<ACE_CDR::ULong>(data.tag_ids.size());
	good_bit = good_bit && cdr.write_ulong_array(data.tag_ids.data(), data.tag_ids.size());
	
	return good_bit;
}

// de-serialization operator for element CommDetectedMarkerEventParameter
ACE_CDR::Boolean operator>>(ACE_InputCDR &cdr, CommTrackingObjectsIDL::CommDetectedMarkerEventParameter &data)
{
	ACE_CDR::Boolean good_bit = true;
	// deserialize list-type element tag_ids
	ACE_CDR::ULong data_tag_idsNbr;
	good_bit = good_bit && cdr >> data_tag_idsNbr;
	data.tag_ids.resize(data_tag_idsNbr);
	good_bit = good_bit && cdr.read_ulong_array(data.tag_ids.data(), data_tag_idsNbr);
	
	return good_bit;
}

// serialization operator for CommunicationObject CommDetectedMarkerEventParameter
ACE_CDR::Boolean operator<<(ACE_OutputCDR &cdr, const CommTrackingObjects::CommDetectedMarkerEventParameter &obj)
{
	return cdr << obj.get();
}

// de-serialization operator for CommunicationObject CommDetectedMarkerEventParameter
ACE_CDR::Boolean operator>>(ACE_InputCDR &cdr, CommTrackingObjects::CommDetectedMarkerEventParameter &obj)
{
	return cdr >> obj.set();
}
