//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef COMMTRACKINGOBJECTS_PERSONMANAGERPARAM_ENUM_H_
#define COMMTRACKINGOBJECTS_PERSONMANAGERPARAM_ENUM_H_

#include <CommTrackingObjects/enumPersonManagerParamData.hh>

#include <string>
#include <iostream>

// SmartUtils used in from_xml method
#include "smartKnuthMorrisPratt.hh"

namespace CommTrackingObjects {
	
	class PersonManagerParam {
	private:
		CommTrackingObjectsIDL::PersonManagerParam value;
		
	public:
		enum ENUM_PersonManagerParam {
			ENUM_VALUE_UNDEFINED = 0,
			NONE_MANAGER_PARAM = 1,
			RESET_MANAGER = 2,
			DEACTIVATE_MANAGER = 3,
			ACTIVATE_MANAGER = 4
		};
		
		// default constructor
		PersonManagerParam() { 
			value = ENUM_VALUE_UNDEFINED;
		}
		
		// copy constructor for enum type
		PersonManagerParam(ENUM_PersonManagerParam e) {
			value = static_cast<int>(e);
		}
		
		// copy constructor for IDL type
		PersonManagerParam(CommTrackingObjectsIDL::PersonManagerParam e) {
			value = e;
		}
		
		//const CommTrackingObjectsIDL::PersonManagerParam& get() const { return value; }
		
		// ENUM operator
		operator ENUM_PersonManagerParam() const {
			return static_cast<ENUM_PersonManagerParam>(value);
		}
		
		// compare operator
		bool operator == (const ENUM_PersonManagerParam t) const {
			return this->value == t;
		}
		
		std::string to_string() const {
			std::string result = "";
			switch (value) {
				case NONE_MANAGER_PARAM:
					result = "PersonManagerParam::NONE_MANAGER_PARAM";
					break;
				case RESET_MANAGER:
					result = "PersonManagerParam::RESET_MANAGER";
					break;
				case DEACTIVATE_MANAGER:
					result = "PersonManagerParam::DEACTIVATE_MANAGER";
					break;
				case ACTIVATE_MANAGER:
					result = "PersonManagerParam::ACTIVATE_MANAGER";
					break;
				default:
					result = "ENUM_VALUE_UNDEFINED";
					break;
			};
			return result;
		}
		
		// helper method to easily implement output stream
		void to_ostream(std::ostream &os = std::cout) const {
			os << to_string();
		}
		
		// convert to xml stream
		void to_xml(std::ostream &os, const std::string &indent = "") const {
			os << indent << "<value>" << value << "</value>";
		}
		
		// restore from xml stream
		void from_xml(std::istream &is) {
			static const Smart::KnuthMorrisPratt kmp_value("<value>");
			if(kmp_value.search(is)) {
				is >> value;
			}
		}
	
	};
	
	inline std::ostream &operator<<(std::ostream &os, const PersonManagerParam &e)
	{
		e.to_ostream(os);
		return os;
	}
};

#endif
