//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#include "CommTrackingObjects/PersonDetectionEventStateACE.hh"
#include <ace/SString.h>

// serialization operator for element PersonDetectionEventState
ACE_CDR::Boolean operator<<(ACE_OutputCDR &cdr, const CommTrackingObjectsIDL::PersonDetectionEventState &data)
{
	ACE_CDR::Boolean good_bit = true;
	// serialize list-element environment_id
	good_bit = good_bit && cdr.write_ulong(data.environment_id);
	// serialize list-element person_id
	good_bit = good_bit && cdr << ACE_Utils::truncate_cast<ACE_CDR::ULong>(data.person_id.size());
	good_bit = good_bit && cdr.write_ulong_array(data.person_id.data(), data.person_id.size());
	
	return good_bit;
}

// de-serialization operator for element PersonDetectionEventState
ACE_CDR::Boolean operator>>(ACE_InputCDR &cdr, CommTrackingObjectsIDL::PersonDetectionEventState &data)
{
	ACE_CDR::Boolean good_bit = true;
	// deserialize type element environment_id
	good_bit = good_bit && cdr.read_ulong(data.environment_id);
	// deserialize list-type element person_id
	ACE_CDR::ULong data_person_idNbr;
	good_bit = good_bit && cdr >> data_person_idNbr;
	data.person_id.resize(data_person_idNbr);
	good_bit = good_bit && cdr.read_ulong_array(data.person_id.data(), data_person_idNbr);
	
	return good_bit;
}

// serialization operator for CommunicationObject PersonDetectionEventState
ACE_CDR::Boolean operator<<(ACE_OutputCDR &cdr, const CommTrackingObjects::PersonDetectionEventState &obj)
{
	return cdr << obj.get();
}

// de-serialization operator for CommunicationObject PersonDetectionEventState
ACE_CDR::Boolean operator>>(ACE_InputCDR &cdr, CommTrackingObjects::PersonDetectionEventState &obj)
{
	return cdr >> obj.set();
}
