//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#include "CommManipulationPlannerObjects/CommManipulationPlannerEventParameterACE.hh"
#include <ace/SString.h>
#include "CommManipulationPlannerObjects/enumManipulationPlannerEventData.hh"

// serialization operator for element CommManipulationPlannerEventParameter
ACE_CDR::Boolean operator<<(ACE_OutputCDR &cdr, const CommManipulationPlannerObjectsIDL::CommManipulationPlannerEventParameter &data)
{
	ACE_CDR::Boolean good_bit = true;
	// serialize list-element event
	good_bit = good_bit && cdr.write_long(data.event);
	
	return good_bit;
}

// de-serialization operator for element CommManipulationPlannerEventParameter
ACE_CDR::Boolean operator>>(ACE_InputCDR &cdr, CommManipulationPlannerObjectsIDL::CommManipulationPlannerEventParameter &data)
{
	ACE_CDR::Boolean good_bit = true;
	// deserialize type element event
	good_bit = good_bit && cdr.read_long(data.event);
	
	return good_bit;
}

// serialization operator for CommunicationObject CommManipulationPlannerEventParameter
ACE_CDR::Boolean operator<<(ACE_OutputCDR &cdr, const CommManipulationPlannerObjects::CommManipulationPlannerEventParameter &obj)
{
	return cdr << obj.get();
}

// de-serialization operator for CommunicationObject CommManipulationPlannerEventParameter
ACE_CDR::Boolean operator>>(ACE_InputCDR &cdr, CommManipulationPlannerObjects::CommManipulationPlannerEventParameter &obj)
{
	return cdr >> obj.set();
}
