//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef COMMNAVIGATIONOBJECTS_COMMNAVIGATIONTOPOLOGYCONNECTION_CORE_H_
#define COMMNAVIGATIONOBJECTS_COMMNAVIGATIONTOPOLOGYCONNECTION_CORE_H_

#include "CommNavigationObjects/CommNavigationTopologyConnectionData.hh"
#include "CommNavigationObjects/enumNavigationConnectonType.hh"

#include <iostream>
#include <string>
#include <list>

namespace CommNavigationObjects {
	
class CommNavigationTopologyConnectionCore {
protected:
	// data structure
	CommNavigationObjectsIDL::CommNavigationTopologyConnection idl_CommNavigationTopologyConnection;
	
public:
	// give a publicly accessible type-name for the template parameter IDL
	typedef CommNavigationObjectsIDL::CommNavigationTopologyConnection DATATYPE;
	
	#ifdef ENABLE_HASH
		static size_t generateDataHash(const DATATYPE &);
	#endif
	
	static const char* getCompiledHash();
	static void getAllHashValues(std::list<std::string> &hashes);
	static void checkAllHashValues(std::list<std::string> &hashes);
	
	// default constructors
	CommNavigationTopologyConnectionCore();
	CommNavigationTopologyConnectionCore(const DATATYPE &data);
	// default destructor
	virtual ~CommNavigationTopologyConnectionCore();
	
	const DATATYPE& get() const { return idl_CommNavigationTopologyConnection; }
	operator const DATATYPE&() const { return idl_CommNavigationTopologyConnection; }
	DATATYPE& set() { return idl_CommNavigationTopologyConnection; }

	static inline std::string identifier(void) { return "CommNavigationObjects::CommNavigationTopologyConnection"; }
	
	// helper method to easily implement output stream in derived classes
	void to_ostream(std::ostream &os = std::cout) const;
	
	// convert to xml stream
	void to_xml(std::ostream &os, const std::string &indent = "") const;
	
	// restore from xml stream
	void from_xml(std::istream &is);
	
	// User Interface
	
	// getter and setter for element Type
	inline CommNavigationObjects::NavigationConnectonType getType() const { return CommNavigationObjects::NavigationConnectonType(idl_CommNavigationTopologyConnection.type); }
	inline CommNavigationTopologyConnectionCore& setType(const CommNavigationObjects::NavigationConnectonType &type) { idl_CommNavigationTopologyConnection.type = type; return *this; }
	
	// getter and setter for element LocationId
	inline unsigned int getLocationId() const { return idl_CommNavigationTopologyConnection.locationId; }
	inline CommNavigationTopologyConnectionCore& setLocationId(const unsigned int &locationId) { idl_CommNavigationTopologyConnection.locationId = locationId; return *this; }
	
	// getter and setter for element FromPart
	inline unsigned int getFromPart() const { return idl_CommNavigationTopologyConnection.fromPart; }
	inline CommNavigationTopologyConnectionCore& setFromPart(const unsigned int &fromPart) { idl_CommNavigationTopologyConnection.fromPart = fromPart; return *this; }
	
	// getter and setter for element ToPart
	inline unsigned int getToPart() const { return idl_CommNavigationTopologyConnection.toPart; }
	inline CommNavigationTopologyConnectionCore& setToPart(const unsigned int &toPart) { idl_CommNavigationTopologyConnection.toPart = toPart; return *this; }
};

} /* namespace CommNavigationObjects */
#endif /* COMMNAVIGATIONOBJECTS_COMMNAVIGATIONTOPOLOGYCONNECTION_CORE_H_ */
