//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef COMMNAVIGATIONOBJECTS_COMMNAVIGATIONTOPOLOGYMAP_DATA_H_
#define COMMNAVIGATIONOBJECTS_COMMNAVIGATIONTOPOLOGYMAP_DATA_H_

#include "CommNavigationObjects/CommNavigationTopologyConnectionData.hh"
#include "CommNavigationObjects/CommNavigationTopologyPartData.hh"

#include <vector>

namespace CommNavigationObjectsIDL 
{
	typedef std::vector<CommNavigationObjectsIDL::CommNavigationTopologyPart> CommNavigationTopologyMap_vertices_type;
	typedef std::vector<CommNavigationObjectsIDL::CommNavigationTopologyConnection> CommNavigationTopologyMap_edges_type;
	struct CommNavigationTopologyMap
	{
		bool isValid;
		CommNavigationTopologyMap_vertices_type vertices;
		CommNavigationTopologyMap_edges_type edges;
  	};
};

#endif /* COMMNAVIGATIONOBJECTS_COMMNAVIGATIONTOPOLOGYMAP_DATA_H_ */
