//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef COMMNAVIGATIONOBJECTS_CDLGOALEVENTTYPE_ENUM_H_
#define COMMNAVIGATIONOBJECTS_CDLGOALEVENTTYPE_ENUM_H_

#include <CommNavigationObjects/enumCdlGoalEventTypeData.hh>

#include <string>
#include <iostream>

// SmartUtils used in from_xml method
#include "smartKnuthMorrisPratt.hh"

namespace CommNavigationObjects {
	
	class CdlGoalEventType {
	private:
		CommNavigationObjectsIDL::CdlGoalEventType value;
		
	public:
		enum ENUM_CdlGoalEventType {
			ENUM_VALUE_UNDEFINED = 0,
			CDL_GOAL_UNKNOWN = 1,
			CDL_GOAL_REACHED = 2,
			CDL_GOAL_NOT_REACHED = 3
		};
		
		// default constructor
		CdlGoalEventType() { 
			value = ENUM_VALUE_UNDEFINED;
		}
		
		// copy constructor for enum type
		CdlGoalEventType(ENUM_CdlGoalEventType e) {
			value = static_cast<int>(e);
		}
		
		// copy constructor for IDL type
		CdlGoalEventType(CommNavigationObjectsIDL::CdlGoalEventType e) {
			value = e;
		}
		
		//const CommNavigationObjectsIDL::CdlGoalEventType& get() const { return value; }
		
		// ENUM operator
		operator ENUM_CdlGoalEventType() const {
			return static_cast<ENUM_CdlGoalEventType>(value);
		}
		
		// compare operator
		bool operator == (const ENUM_CdlGoalEventType t) const {
			return this->value == t;
		}
		
		std::string to_string() const {
			std::string result = "";
			switch (value) {
				case CDL_GOAL_UNKNOWN:
					result = "CdlGoalEventType::CDL_GOAL_UNKNOWN";
					break;
				case CDL_GOAL_REACHED:
					result = "CdlGoalEventType::CDL_GOAL_REACHED";
					break;
				case CDL_GOAL_NOT_REACHED:
					result = "CdlGoalEventType::CDL_GOAL_NOT_REACHED";
					break;
				default:
					result = "ENUM_VALUE_UNDEFINED";
					break;
			};
			return result;
		}
		
		// helper method to easily implement output stream
		void to_ostream(std::ostream &os = std::cout) const {
			os << to_string();
		}
		
		// convert to xml stream
		void to_xml(std::ostream &os, const std::string &indent = "") const {
			os << indent << "<value>" << value << "</value>";
		}
		
		// restore from xml stream
		void from_xml(std::istream &is) {
			static const Smart::KnuthMorrisPratt kmp_value("<value>");
			if(kmp_value.search(is)) {
				is >> value;
			}
		}
	
	};
	
	inline std::ostream &operator<<(std::ostream &os, const CdlGoalEventType &e)
	{
		e.to_ostream(os);
		return os;
	}
};

#endif
