//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef COMMPTUOBJECTS_COMMPTUSTATE_DATA_H_
#define COMMPTUOBJECTS_COMMPTUSTATE_DATA_H_

#include "CommBasicObjects/CommPose3dData.hh"


namespace CommPTUObjectsIDL 
{
	struct CommPTUState
	{
		double pan;
		double tilt;
		CommBasicObjectsIDL::CommPose3d pose_PTU;
		bool is_valid;
  	};
};

#endif /* COMMPTUOBJECTS_COMMPTUSTATE_DATA_H_ */
