//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef COMMPTUOBJECTS_COMMPTUGOALEVENTPARAMETER_CORE_H_
#define COMMPTUOBJECTS_COMMPTUGOALEVENTPARAMETER_CORE_H_

#include "CommPTUObjects/CommPTUGoalEventParameterData.hh"
#include "CommPTUObjects/enumPTUMoveStatus.hh"

#include <iostream>
#include <string>
#include <list>

namespace CommPTUObjects {
	
class CommPTUGoalEventParameterCore {
protected:
	// data structure
	CommPTUObjectsIDL::CommPTUGoalEventParameter idl_CommPTUGoalEventParameter;
	
public:
	// give a publicly accessible type-name for the template parameter IDL
	typedef CommPTUObjectsIDL::CommPTUGoalEventParameter DATATYPE;
	
	#ifdef ENABLE_HASH
		static size_t generateDataHash(const DATATYPE &);
	#endif
	
	static const char* getCompiledHash();
	static void getAllHashValues(std::list<std::string> &hashes);
	static void checkAllHashValues(std::list<std::string> &hashes);
	
	// default constructors
	CommPTUGoalEventParameterCore();
	CommPTUGoalEventParameterCore(const DATATYPE &data);
	// default destructor
	virtual ~CommPTUGoalEventParameterCore();
	
	const DATATYPE& get() const { return idl_CommPTUGoalEventParameter; }
	operator const DATATYPE&() const { return idl_CommPTUGoalEventParameter; }
	DATATYPE& set() { return idl_CommPTUGoalEventParameter; }

	static inline std::string identifier(void) { return "CommPTUObjects::CommPTUGoalEventParameter"; }
	
	// helper method to easily implement output stream in derived classes
	void to_ostream(std::ostream &os = std::cout) const;
	
	// convert to xml stream
	void to_xml(std::ostream &os, const std::string &indent = "") const;
	
	// restore from xml stream
	void from_xml(std::istream &is);
	
	// User Interface
	
	// getter and setter for element OldState
	inline CommPTUObjects::PTUMoveStatus getOldState() const { return CommPTUObjects::PTUMoveStatus(idl_CommPTUGoalEventParameter.oldState); }
	inline CommPTUGoalEventParameterCore& setOldState(const CommPTUObjects::PTUMoveStatus &oldState) { idl_CommPTUGoalEventParameter.oldState = oldState; return *this; }
};

} /* namespace CommPTUObjects */
#endif /* COMMPTUOBJECTS_COMMPTUGOALEVENTPARAMETER_CORE_H_ */
