//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef COMMPTUOBJECTS_COMMMOBILEPTUSTATE_ACE_H_
#define COMMPTUOBJECTS_COMMMOBILEPTUSTATE_ACE_H_

#include "CommPTUObjects/CommMobilePTUState.hh"

#include <ace/CDR_Stream.h>

// serialization operator for DataStructure CommMobilePTUState
ACE_CDR::Boolean operator<<(ACE_OutputCDR &cdr, const CommPTUObjectsIDL::CommMobilePTUState &data);

// de-serialization operator for DataStructure CommMobilePTUState
ACE_CDR::Boolean operator>>(ACE_InputCDR &cdr, CommPTUObjectsIDL::CommMobilePTUState &data);

// serialization operator for CommunicationObject CommMobilePTUState
ACE_CDR::Boolean operator<<(ACE_OutputCDR &cdr, const CommPTUObjects::CommMobilePTUState &obj);

// de-serialization operator for CommunicationObject CommMobilePTUState
ACE_CDR::Boolean operator>>(ACE_InputCDR &cdr, CommPTUObjects::CommMobilePTUState &obj);

#endif /* COMMPTUOBJECTS_COMMMOBILEPTUSTATE_ACE_H_ */
