//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Christian Schlegel (schlegel@hs-ulm.de)
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------

#include "CommRobotinoObjects/CommPlannerGoalList.hh"
#include <SeRoNet/CommunicationObjects/Description/SelfDescription.hpp>
#include <SeRoNet/CommunicationObjects/Description/ElementPrimitives.hpp>
#pragma once


namespace SeRoNet {
namespace CommunicationObjects {
namespace Description {
// serialization for CommPlannerGoalList
template <>
ComplexType::shp_t SelfDescription(CommRobotinoObjects::CommPlannerGoalList *obj, std::string name)
{
	auto ret = std::make_shared<SeRoNet::CommunicationObjects::Description::ComplexType>(name);
	/// \todo check for ComplexObjects
	// add id
	ret->add(
		SeRoNet::CommunicationObjects::Description::IDescription::shp_t(
			new SeRoNet::CommunicationObjects::Description::ElementInt32(
				"id",
				std::bind(&CommRobotinoObjects::CommPlannerGoalList::getId, obj),
				std::bind(&CommRobotinoObjects::CommPlannerGoalList::setId, obj, std::placeholders::_1)
			)
		)
	);
	// add flag
	ret->add(
		SeRoNet::CommunicationObjects::Description::IDescription::shp_t(
			new SeRoNet::CommunicationObjects::Description::ElementInt32(
				"flag",
				std::bind(&CommRobotinoObjects::CommPlannerGoalList::getFlag, obj),
				std::bind(&CommRobotinoObjects::CommPlannerGoalList::setFlag, obj, std::placeholders::_1)
			)
		)
	);
	// add goalXvector
	ret->add(
		SeRoNet::CommunicationObjects::Description::IDescription::shp_t(
			new SeRoNet::CommunicationObjects::Description::ElementDouble(
				"goalXvector",
				std::bind(&CommRobotinoObjects::CommPlannerGoalList::getGoalXvector, obj),
				std::bind(&CommRobotinoObjects::CommPlannerGoalList::setGoalXvector, obj, std::placeholders::_1)
			)
		)
	);
	// add goalYvector
	ret->add(
		SeRoNet::CommunicationObjects::Description::IDescription::shp_t(
			new SeRoNet::CommunicationObjects::Description::ElementDouble(
				"goalYvector",
				std::bind(&CommRobotinoObjects::CommPlannerGoalList::getGoalYvector, obj),
				std::bind(&CommRobotinoObjects::CommPlannerGoalList::setGoalYvector, obj, std::placeholders::_1)
			)
		)
	);
	// add nodeObstacleVector
	ret->add(
		SeRoNet::CommunicationObjects::Description::IDescription::shp_t(
			new SeRoNet::CommunicationObjects::Description::ElementDouble(
				"nodeObstacleVector",
				std::bind(&CommRobotinoObjects::CommPlannerGoalList::getNodeObstacleVector, obj),
				std::bind(&CommRobotinoObjects::CommPlannerGoalList::setNodeObstacleVector, obj, std::placeholders::_1)
			)
		)
	);
	// add finalGoalX
	ret->add(
		SeRoNet::CommunicationObjects::Description::IDescription::shp_t(
			new SeRoNet::CommunicationObjects::Description::ElementDouble(
				"finalGoalX",
				std::bind(&CommRobotinoObjects::CommPlannerGoalList::getFinalGoalX, obj),
				std::bind(&CommRobotinoObjects::CommPlannerGoalList::setFinalGoalX, obj, std::placeholders::_1)
			)
		)
	);
	// add finalGoalY
	ret->add(
		SeRoNet::CommunicationObjects::Description::IDescription::shp_t(
			new SeRoNet::CommunicationObjects::Description::ElementDouble(
				"finalGoalY",
				std::bind(&CommRobotinoObjects::CommPlannerGoalList::getFinalGoalY, obj),
				std::bind(&CommRobotinoObjects::CommPlannerGoalList::setFinalGoalY, obj, std::placeholders::_1)
			)
		)
	);
	return ret;
} // end SelfDescription
} // end namespace Description
} // end namespace CommunicationObjects
} // end namespace SeRoNet
