//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Christian Schlegel (schlegel@hs-ulm.de)
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------

#include "CommRobotinoObjects/CommRobotinoIOValues.hh"
#include <SeRoNet/CommunicationObjects/Description/SelfDescription.hpp>
#include <SeRoNet/CommunicationObjects/Description/ElementPrimitives.hpp>
#pragma once

#include "CommRobotinoObjects/AnalogOutputRequestOpcUa.hh"
#include "CommRobotinoObjects/DigitalOutputRequestOpcUa.hh"

namespace SeRoNet {
namespace CommunicationObjects {
namespace Description {
// serialization for CommRobotinoIOValues
template <>
ComplexType::shp_t SelfDescription(CommRobotinoObjects::CommRobotinoIOValues *obj, std::string name)
{
	auto ret = std::make_shared<SeRoNet::CommunicationObjects::Description::ComplexType>(name);
	/// \todo check for ComplexObjects
	// add analogInputValues
	ret->add(
		SeRoNet::CommunicationObjects::Description::IDescription::shp_t(
			new SeRoNet::CommunicationObjects::Description::ElementFloat(
				"analogInputValues",
				std::bind(&CommRobotinoObjects::CommRobotinoIOValues::getAnalogInputValues, obj),
				std::bind(&CommRobotinoObjects::CommRobotinoIOValues::setAnalogInputValues, obj, std::placeholders::_1)
			)
		)
	);
	// add digitalInputValues
	ret->add(
		SeRoNet::CommunicationObjects::Description::IDescription::shp_t(
			new SeRoNet::CommunicationObjects::Description::ElementBool(
				"digitalInputValues",
				std::bind(&CommRobotinoObjects::CommRobotinoIOValues::getDigitalInputValues, obj),
				std::bind(&CommRobotinoObjects::CommRobotinoIOValues::setDigitalInputValues, obj, std::placeholders::_1)
			)
		)
	);
	ret->add(
		SelfDescription(&(obj->getAnalogOutputValues()), "AnalogOutputRequest")
	);
	ret->add(
		SelfDescription(&(obj->getDigitalOutputValues()), "DigitalOutputRequest")
	);
	return ret;
} // end SelfDescription
} // end namespace Description
} // end namespace CommunicationObjects
} // end namespace SeRoNet
