//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#include "DomainSymbolicPlanner/CommSymbolicPlannerPlanACE.hh"
#include <ace/SString.h>

// serialization operator for element CommSymbolicPlannerPlan
ACE_CDR::Boolean operator<<(ACE_OutputCDR &cdr, const DomainSymbolicPlannerIDL::CommSymbolicPlannerPlan &data)
{
	ACE_CDR::Boolean good_bit = true;
	// serialize list-element plan
	good_bit = good_bit && cdr << ACE_CString(data.plan.c_str());
	
	return good_bit;
}

// de-serialization operator for element CommSymbolicPlannerPlan
ACE_CDR::Boolean operator>>(ACE_InputCDR &cdr, DomainSymbolicPlannerIDL::CommSymbolicPlannerPlan &data)
{
	ACE_CDR::Boolean good_bit = true;
	// deserialize string-type element plan
	ACE_CString data_plan_str;
	good_bit = good_bit && cdr >> data_plan_str;
	data.plan = data_plan_str.c_str();
	
	return good_bit;
}

// serialization operator for CommunicationObject CommSymbolicPlannerPlan
ACE_CDR::Boolean operator<<(ACE_OutputCDR &cdr, const DomainSymbolicPlanner::CommSymbolicPlannerPlan &obj)
{
	return cdr << obj.get();
}

// de-serialization operator for CommunicationObject CommSymbolicPlannerPlan
ACE_CDR::Boolean operator>>(ACE_InputCDR &cdr, DomainSymbolicPlanner::CommSymbolicPlannerPlan &obj)
{
	return cdr >> obj.set();
}
