//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef DOMAINFORKLIFT_COMMFORKLIFTEVENTRESULT_ACE_H_
#define DOMAINFORKLIFT_COMMFORKLIFTEVENTRESULT_ACE_H_

#include "DomainForklift/CommForkliftEventResult.hh"

#include <ace/CDR_Stream.h>

// serialization operator for DataStructure CommForkliftEventResult
ACE_CDR::Boolean operator<<(ACE_OutputCDR &cdr, const DomainForkliftIDL::CommForkliftEventResult &data);

// de-serialization operator for DataStructure CommForkliftEventResult
ACE_CDR::Boolean operator>>(ACE_InputCDR &cdr, DomainForkliftIDL::CommForkliftEventResult &data);

// serialization operator for CommunicationObject CommForkliftEventResult
ACE_CDR::Boolean operator<<(ACE_OutputCDR &cdr, const DomainForklift::CommForkliftEventResult &obj);

// de-serialization operator for CommunicationObject CommForkliftEventResult
ACE_CDR::Boolean operator>>(ACE_InputCDR &cdr, DomainForklift::CommForkliftEventResult &obj);

#endif /* DOMAINFORKLIFT_COMMFORKLIFTEVENTRESULT_ACE_H_ */
