//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef DOMAINFORKLIFT_COMMFORKLIFTEVENTRESULT_DATA_H_
#define DOMAINFORKLIFT_COMMFORKLIFTEVENTRESULT_DATA_H_

#include "DomainForklift/enumForkliftEventTypeData.hh"


namespace DomainForkliftIDL 
{
	struct CommForkliftEventResult
	{
		DomainForkliftIDL::ForkliftEventType state;
  	};
};

#endif /* DOMAINFORKLIFT_COMMFORKLIFTEVENTRESULT_DATA_H_ */
