//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef DOMAINVISION_COMM3DPOINTCLOUD_ACE_H_
#define DOMAINVISION_COMM3DPOINTCLOUD_ACE_H_

#include "DomainVision/Comm3dPointCloud.hh"

#include <ace/CDR_Stream.h>

// serialization operator for DataStructure Comm3dPointCloud
ACE_CDR::Boolean operator<<(ACE_OutputCDR &cdr, const DomainVisionIDL::Comm3dPointCloud &data);

// de-serialization operator for DataStructure Comm3dPointCloud
ACE_CDR::Boolean operator>>(ACE_InputCDR &cdr, DomainVisionIDL::Comm3dPointCloud &data);

// serialization operator for CommunicationObject Comm3dPointCloud
ACE_CDR::Boolean operator<<(ACE_OutputCDR &cdr, const DomainVision::Comm3dPointCloud &obj);

// de-serialization operator for CommunicationObject Comm3dPointCloud
ACE_CDR::Boolean operator>>(ACE_InputCDR &cdr, DomainVision::Comm3dPointCloud &obj);

#endif /* DOMAINVISION_COMM3DPOINTCLOUD_ACE_H_ */
