//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef COMMLOCALIZATIONOBJECTS_COMMLOCALIZATIONEVENTRESULT_DATA_H_
#define COMMLOCALIZATIONOBJECTS_COMMLOCALIZATIONEVENTRESULT_DATA_H_

#include "CommLocalizationObjects/enumLocalizationEventTypeData.hh"


namespace CommLocalizationObjectsIDL 
{
	struct CommLocalizationEventResult
	{
		CommLocalizationObjectsIDL::LocalizationEventType state;
  	};
};

#endif /* COMMLOCALIZATIONOBJECTS_COMMLOCALIZATIONEVENTRESULT_DATA_H_ */
