//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef COMMLOCALIZATIONOBJECTS_VIEWPOINTLOCATION_DATA_H_
#define COMMLOCALIZATIONOBJECTS_VIEWPOINTLOCATION_DATA_H_

#include "CommLocalizationObjects/CMatrixDouble22Data.hh"
#include "CommLocalizationObjects/CPose2DData.hh"


namespace CommLocalizationObjectsIDL 
{
	struct ViewpointLocation
	{
		int id;
		CommLocalizationObjectsIDL::CPose2D mean;
		CommLocalizationObjectsIDL::CMatrixDouble22 cov;
		CommLocalizationObjectsIDL::CMatrixDouble22 invCov;
		int observationCount;
		int possibleObservations;
  	};
};

#endif /* COMMLOCALIZATIONOBJECTS_VIEWPOINTLOCATION_DATA_H_ */
