//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Christian Schlegel (schlegel@hs-ulm.de)
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------

#include "CommBasicObjects/CommKBEventParam.hh"
#include <SeRoNet/CommunicationObjects/Description/SelfDescription.hpp>
#include <SeRoNet/CommunicationObjects/Description/ElementPrimitives.hpp>
#pragma once


namespace SeRoNet {
namespace CommunicationObjects {
namespace Description {
// serialization for CommKBEventParam
template <>
ComplexType::shp_t SelfDescription(CommBasicObjects::CommKBEventParam *obj, std::string name)
{
	auto ret = std::make_shared<SeRoNet::CommunicationObjects::Description::ComplexType>(name);
	/// \todo check for ComplexObjects
	// add query
	ret->add(
		SeRoNet::CommunicationObjects::Description::IDescription::shp_t(
			new SeRoNet::CommunicationObjects::Description::ElementString(
				"query",
				std::bind(&CommBasicObjects::CommKBEventParam::getQuery, obj),
				std::bind(&CommBasicObjects::CommKBEventParam::setQuery, obj, std::placeholders::_1)
			)
		)
	);
	// add latestState
	ret->add(
		SeRoNet::CommunicationObjects::Description::IDescription::shp_t(
			new SeRoNet::CommunicationObjects::Description::ElementString(
				"latestState",
				std::bind(&CommBasicObjects::CommKBEventParam::getLatestState, obj),
				std::bind(&CommBasicObjects::CommKBEventParam::setLatestState, obj, std::placeholders::_1)
			)
		)
	);
	// add formatingClause
	ret->add(
		SeRoNet::CommunicationObjects::Description::IDescription::shp_t(
			new SeRoNet::CommunicationObjects::Description::ElementString(
				"formatingClause",
				std::bind(&CommBasicObjects::CommKBEventParam::getFormatingClause, obj),
				std::bind(&CommBasicObjects::CommKBEventParam::setFormatingClause, obj, std::placeholders::_1)
			)
		)
	);
	return ret;
} // end SelfDescription
} // end namespace Description
} // end namespace CommunicationObjects
} // end namespace SeRoNet
