//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// This file is generated once. Modify this file to your needs. 
// If you want the toolchain to re-generate this file, please 
// delete it before running the code generator.
//--------------------------------------------------------------------------
#ifndef COMMLOCALIZATIONOBJECTS_COMMGPSFIX_H_
#define COMMLOCALIZATIONOBJECTS_COMMGPSFIX_H_

#include "CommLocalizationObjects/CommGpsFixCore.hh"

namespace CommLocalizationObjects {
		
class CommGpsFix : public CommGpsFixCore {
	public:
		// default constructors
		CommGpsFix();
		
		/**
		 * Constructor to set all values.
		 * NOTE that you have to keep this constructor consistent with the model!
		 * Use  at your own choice.
		 *
		 * The preferred way to set values for initialization is:
		 *      CommRepository::MyCommObject obj;
		 *      obj.setX(1).setY(2).setZ(3)...;
		 */
		// CommGpsFix(const double &gps_timestamp, const bool &is_2D, const bool &is_3D, const int &satellites_visible, const int &satellites_used, const double &latitude, const double &longitude, const double &altitude, const double &speed, const double &climb, const double &latitude_uncertainty, const double &longitude_uncertainty, const double &altitude_uncertainty, const double &speed_uncertainty, const double &climb_uncertainty);
		
		CommGpsFix(const CommGpsFixCore &commGpsFix);
		CommGpsFix(const DATATYPE &commGpsFix);
		virtual ~CommGpsFix();
		
		// use framework specific getter and setter methods from core (base) class
		using CommGpsFixCore::get;
		using CommGpsFixCore::set;
		
		//
		// feel free to add customized methods here
		//
};

inline std::ostream &operator<<(std::ostream &os, const CommGpsFix &co)
{
	co.to_ostream(os);
	return os;
}
	
} /* namespace CommLocalizationObjects */
#endif /* COMMLOCALIZATIONOBJECTS_COMMGPSFIX_H_ */
