//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// This file is generated once. Modify this file to your needs. 
// If you want the toolchain to re-generate this file, please 
// delete it before running the code generator.
//--------------------------------------------------------------------------

#include "CommLocalizationObjects/CPose2D.hh"

using namespace CommLocalizationObjects;

CPose2D::CPose2D()
:	CPose2DCore()
{  }


/**
 * Constructor to set all values.
 * NOTE that you have to keep this constructor consistent with the model!
 * Use  at your own choice.
 *
 * The preferred way to set values for initialization is:
 *      CommRepository::MyCommObject obj;
 *      obj.setX(1).setY(2).setZ(3)...;
CPose2D::CPose2D(const double &m_phi, const bool &m_is3D, const double &m_x, const double &m_y, const double &m_z)
:	CPose2DCore() // base constructor sets default values as defined in the model
{
	setM_phi(m_phi);
	setM_is3D(m_is3D);
	setM_x(m_x);
	setM_y(m_y);
	setM_z(m_z);
}
 */

CPose2D::CPose2D(const CPose2DCore &cPose2D)
:	CPose2DCore(cPose2D)
{  }

CPose2D::CPose2D(const DATATYPE &cPose2D)
:	CPose2DCore(cPose2D)
{  }

CPose2D::~CPose2D()
{  }
