//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// This file is generated once. Modify this file to your needs. 
// If you want the toolchain to re-generate this file, please 
// delete it before running the code generator.
//--------------------------------------------------------------------------
#ifndef COMMLOCALIZATIONOBJECTS_VIEWPOINTLOCATION_H_
#define COMMLOCALIZATIONOBJECTS_VIEWPOINTLOCATION_H_

#include "CommLocalizationObjects/ViewpointLocationCore.hh"

namespace CommLocalizationObjects {
		
class ViewpointLocation : public ViewpointLocationCore {
	public:
		// default constructors
		ViewpointLocation();
		
		/**
		 * Constructor to set all values.
		 * NOTE that you have to keep this constructor consistent with the model!
		 * Use  at your own choice.
		 *
		 * The preferred way to set values for initialization is:
		 *      CommRepository::MyCommObject obj;
		 *      obj.setX(1).setY(2).setZ(3)...;
		 */
		// ViewpointLocation(const int &id, const CommLocalizationObjects::CPose2D &mean, const CommLocalizationObjects::CMatrixDouble22 &cov, const CommLocalizationObjects::CMatrixDouble22 &invCov, const int &observationCount, const int &possibleObservations);
		
		ViewpointLocation(const ViewpointLocationCore &viewpointLocation);
		ViewpointLocation(const DATATYPE &viewpointLocation);
		virtual ~ViewpointLocation();
		
		// use framework specific getter and setter methods from core (base) class
		using ViewpointLocationCore::get;
		using ViewpointLocationCore::set;
		
		//
		// feel free to add customized methods here
		//
};

inline std::ostream &operator<<(std::ostream &os, const ViewpointLocation &co)
{
	co.to_ostream(os);
	return os;
}
	
} /* namespace CommLocalizationObjects */
#endif /* COMMLOCALIZATIONOBJECTS_VIEWPOINTLOCATION_H_ */
