//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef COMMOBJECTRECOGNITIONOBJECTS_COMMOBJECTBELIEF_CORE_H_
#define COMMOBJECTRECOGNITIONOBJECTS_COMMOBJECTBELIEF_CORE_H_

#include "CommObjectRecognitionObjects/CommObjectBeliefData.hh"
#include "CommBasicObjects/CommPose3d.hh"

#include <iostream>
#include <string>
#include <list>

namespace CommObjectRecognitionObjects {
	
class CommObjectBeliefCore {
protected:
	// data structure
	CommObjectRecognitionObjectsIDL::CommObjectBelief idl_CommObjectBelief;
	
public:
	// give a publicly accessible type-name for the template parameter IDL
	typedef CommObjectRecognitionObjectsIDL::CommObjectBelief DATATYPE;
	
	#ifdef ENABLE_HASH
		static size_t generateDataHash(const DATATYPE &);
	#endif
	
	static const char* getCompiledHash();
	static void getAllHashValues(std::list<std::string> &hashes);
	static void checkAllHashValues(std::list<std::string> &hashes);
	
	// default constructors
	CommObjectBeliefCore();
	CommObjectBeliefCore(const DATATYPE &data);
	// default destructor
	virtual ~CommObjectBeliefCore();
	
	const DATATYPE& get() const { return idl_CommObjectBelief; }
	operator const DATATYPE&() const { return idl_CommObjectBelief; }
	DATATYPE& set() { return idl_CommObjectBelief; }

	static inline std::string identifier(void) { return "CommObjectRecognitionObjects::CommObjectBelief"; }
	
	// helper method to easily implement output stream in derived classes
	void to_ostream(std::ostream &os = std::cout) const;
	
	// convert to xml stream
	void to_xml(std::ostream &os, const std::string &indent = "") const;
	
	// restore from xml stream
	void from_xml(std::istream &is);
	
	// User Interface
	
	// getter and setter for element Type
	inline std::string getType() const { return idl_CommObjectBelief.type; }
	inline CommObjectBeliefCore& setType(const std::string &type) { idl_CommObjectBelief.type = type; return *this; }
	
	// getter and setter for element Probability
	inline double getProbability() const { return idl_CommObjectBelief.probability; }
	inline CommObjectBeliefCore& setProbability(const double &probability) { idl_CommObjectBelief.probability = probability; return *this; }
	
	// getter and setter for element Pose
	inline CommBasicObjects::CommPose3d getPose() const { return CommBasicObjects::CommPose3d(idl_CommObjectBelief.pose); }
	inline CommObjectBeliefCore& setPose(const CommBasicObjects::CommPose3d &pose) { idl_CommObjectBelief.pose = pose; return *this; }
	
	// getter and setter for element Cov
	/**
	 * Getter methods for idl_CommObjectBelief.cov of type vector<double>
	 */
	inline std::vector<double>& getCovRef() { return idl_CommObjectBelief.cov; }
	inline std::vector<double> getCovCopy() const {
		return std::vector<double>(idl_CommObjectBelief.cov.begin(), idl_CommObjectBelief.cov.end());
	}
	inline double getCovElemAtPos(const size_t &pos) const { return idl_CommObjectBelief.cov[pos]; }
	inline size_t getCovSize() const { return idl_CommObjectBelief.cov.size(); }
	inline bool isCovEmpty() const { return idl_CommObjectBelief.cov.empty(); }
	/**
	 * Setter methods for idl_CommObjectBelief.cov of type vector<double>
	 */
	inline CommObjectBeliefCore& setCov(const std::vector<double> &cov) { idl_CommObjectBelief.cov = cov; return *this; }
	inline bool setCovElemAtPos(const size_t &pos, const double &elem) {
		if(pos < idl_CommObjectBelief.cov.size()) {
			idl_CommObjectBelief.cov[pos] = elem;
			return true;
		}
		return false;
	}
	inline bool insertCovVectorAtPos(const size_t &pos, const std::vector<double> &data) {
		if(pos < idl_CommObjectBelief.cov.size()) {
			idl_CommObjectBelief.cov.insert(idl_CommObjectBelief.cov.begin()+pos, data.begin(), data.end());
			return true;
		}
		return false;
	}
	inline void resizeCov(const size_t &size) { idl_CommObjectBelief.cov.resize(size); }
	inline bool eraseCovElemsAtPos(const size_t &pos, const size_t &nbr_elems) {
		if( (pos+nbr_elems) <= idl_CommObjectBelief.cov.size() ) {
			idl_CommObjectBelief.cov.erase(idl_CommObjectBelief.cov.begin()+pos, idl_CommObjectBelief.cov.begin()+pos+nbr_elems);
			return true;
		}
		return false;
	}
	inline void clearCov() { idl_CommObjectBelief.cov.clear(); }
	
	// getter and setter for element ValidPosePdf
	inline bool getValidPosePdf() const { return idl_CommObjectBelief.validPosePdf; }
	inline CommObjectBeliefCore& setValidPosePdf(const bool &validPosePdf) { idl_CommObjectBelief.validPosePdf = validPosePdf; return *this; }
};

} /* namespace CommObjectRecognitionObjects */
#endif /* COMMOBJECTRECOGNITIONOBJECTS_COMMOBJECTBELIEF_CORE_H_ */
