//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#include "CommObjectRecognitionObjects/CommOcrTextACE.hh"
#include <ace/SString.h>

// serialization operator for element CommOcrText
ACE_CDR::Boolean operator<<(ACE_OutputCDR &cdr, const CommObjectRecognitionObjectsIDL::CommOcrText &data)
{
	ACE_CDR::Boolean good_bit = true;
	// serialize list-element text
	good_bit = good_bit && cdr << ACE_CString(data.text.c_str());
	// serialize list-element belief
	good_bit = good_bit && cdr.write_double(data.belief);
	
	return good_bit;
}

// de-serialization operator for element CommOcrText
ACE_CDR::Boolean operator>>(ACE_InputCDR &cdr, CommObjectRecognitionObjectsIDL::CommOcrText &data)
{
	ACE_CDR::Boolean good_bit = true;
	// deserialize string-type element text
	ACE_CString data_text_str;
	good_bit = good_bit && cdr >> data_text_str;
	data.text = data_text_str.c_str();
	// deserialize type element belief
	good_bit = good_bit && cdr.read_double(data.belief);
	
	return good_bit;
}

// serialization operator for CommunicationObject CommOcrText
ACE_CDR::Boolean operator<<(ACE_OutputCDR &cdr, const CommObjectRecognitionObjects::CommOcrText &obj)
{
	return cdr << obj.get();
}

// de-serialization operator for CommunicationObject CommOcrText
ACE_CDR::Boolean operator>>(ACE_InputCDR &cdr, CommObjectRecognitionObjects::CommOcrText &obj)
{
	return cdr >> obj.set();
}
