//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef COMMOBJECTRECOGNITIONOBJECTS_COMMOBJECTRECOGNITIONEVENTRESULT_CORE_H_
#define COMMOBJECTRECOGNITIONOBJECTS_COMMOBJECTRECOGNITIONEVENTRESULT_CORE_H_

#include "CommObjectRecognitionObjects/CommObjectRecognitionEventResultData.hh"
#include "CommObjectRecognitionObjects/enumObjectRecognitionState.hh"

#include <iostream>
#include <string>
#include <list>

namespace CommObjectRecognitionObjects {
	
class CommObjectRecognitionEventResultCore {
protected:
	// data structure
	CommObjectRecognitionObjectsIDL::CommObjectRecognitionEventResult idl_CommObjectRecognitionEventResult;
	
public:
	// give a publicly accessible type-name for the template parameter IDL
	typedef CommObjectRecognitionObjectsIDL::CommObjectRecognitionEventResult DATATYPE;
	
	#ifdef ENABLE_HASH
		static size_t generateDataHash(const DATATYPE &);
	#endif
	
	static const char* getCompiledHash();
	static void getAllHashValues(std::list<std::string> &hashes);
	static void checkAllHashValues(std::list<std::string> &hashes);
	
	// default constructors
	CommObjectRecognitionEventResultCore();
	CommObjectRecognitionEventResultCore(const DATATYPE &data);
	// default destructor
	virtual ~CommObjectRecognitionEventResultCore();
	
	const DATATYPE& get() const { return idl_CommObjectRecognitionEventResult; }
	operator const DATATYPE&() const { return idl_CommObjectRecognitionEventResult; }
	DATATYPE& set() { return idl_CommObjectRecognitionEventResult; }

	static inline std::string identifier(void) { return "CommObjectRecognitionObjects::CommObjectRecognitionEventResult"; }
	
	// helper method to easily implement output stream in derived classes
	void to_ostream(std::ostream &os = std::cout) const;
	
	// convert to xml stream
	void to_xml(std::ostream &os, const std::string &indent = "") const;
	
	// restore from xml stream
	void from_xml(std::istream &is);
	
	// User Interface
	
	// getter and setter for element State
	inline CommObjectRecognitionObjects::ObjectRecognitionState getState() const { return CommObjectRecognitionObjects::ObjectRecognitionState(idl_CommObjectRecognitionEventResult.state); }
	inline CommObjectRecognitionEventResultCore& setState(const CommObjectRecognitionObjects::ObjectRecognitionState &state) { idl_CommObjectRecognitionEventResult.state = state; return *this; }
	
	// getter and setter for element Environment_id
	inline unsigned int getEnvironment_id() const { return idl_CommObjectRecognitionEventResult.environment_id; }
	inline CommObjectRecognitionEventResultCore& setEnvironment_id(const unsigned int &environment_id) { idl_CommObjectRecognitionEventResult.environment_id = environment_id; return *this; }
	
	// getter and setter for element Object_id
	/**
	 * Getter methods for idl_CommObjectRecognitionEventResult.object_id of type vector<unsigned int>
	 */
	inline std::vector<unsigned int>& getObject_idRef() { return idl_CommObjectRecognitionEventResult.object_id; }
	inline std::vector<unsigned int> getObject_idCopy() const {
		return std::vector<unsigned int>(idl_CommObjectRecognitionEventResult.object_id.begin(), idl_CommObjectRecognitionEventResult.object_id.end());
	}
	inline unsigned int getObject_idElemAtPos(const size_t &pos) const { return idl_CommObjectRecognitionEventResult.object_id[pos]; }
	inline size_t getObject_idSize() const { return idl_CommObjectRecognitionEventResult.object_id.size(); }
	inline bool isObject_idEmpty() const { return idl_CommObjectRecognitionEventResult.object_id.empty(); }
	/**
	 * Setter methods for idl_CommObjectRecognitionEventResult.object_id of type vector<unsigned int>
	 */
	inline CommObjectRecognitionEventResultCore& setObject_id(const std::vector<unsigned int> &object_id) { idl_CommObjectRecognitionEventResult.object_id = object_id; return *this; }
	inline bool setObject_idElemAtPos(const size_t &pos, const unsigned int &elem) {
		if(pos < idl_CommObjectRecognitionEventResult.object_id.size()) {
			idl_CommObjectRecognitionEventResult.object_id[pos] = elem;
			return true;
		}
		return false;
	}
	inline bool insertObject_idVectorAtPos(const size_t &pos, const std::vector<unsigned int> &data) {
		if(pos < idl_CommObjectRecognitionEventResult.object_id.size()) {
			idl_CommObjectRecognitionEventResult.object_id.insert(idl_CommObjectRecognitionEventResult.object_id.begin()+pos, data.begin(), data.end());
			return true;
		}
		return false;
	}
	inline void resizeObject_id(const size_t &size) { idl_CommObjectRecognitionEventResult.object_id.resize(size); }
	inline bool eraseObject_idElemsAtPos(const size_t &pos, const size_t &nbr_elems) {
		if( (pos+nbr_elems) <= idl_CommObjectRecognitionEventResult.object_id.size() ) {
			idl_CommObjectRecognitionEventResult.object_id.erase(idl_CommObjectRecognitionEventResult.object_id.begin()+pos, idl_CommObjectRecognitionEventResult.object_id.begin()+pos+nbr_elems);
			return true;
		}
		return false;
	}
	inline void clearObject_id() { idl_CommObjectRecognitionEventResult.object_id.clear(); }
};

} /* namespace CommObjectRecognitionObjects */
#endif /* COMMOBJECTRECOGNITIONOBJECTS_COMMOBJECTRECOGNITIONEVENTRESULT_CORE_H_ */
