//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// This file is generated once. Modify this file to your needs. 
// If you want the toolchain to re-generate this file, please 
// delete it before running the code generator.
//--------------------------------------------------------------------------
#ifndef COMMROBOTINOOBJECTS_COMMDETECTEDTAGS_H_
#define COMMROBOTINOOBJECTS_COMMDETECTEDTAGS_H_

#include "CommRobotinoObjects/CommDetectedTagsCore.hh"
#include "armadillo.hh"
#include "EulerTransformationMatrices.hh"

namespace CommRobotinoObjects {
		
class CommDetectedTags : public CommDetectedTagsCore {
	public:
		// default constructors
		CommDetectedTags();
		
		/**
		 * Constructor to set all values.
		 * NOTE that you have to keep this constructor consistent with the model!
		 * Use  at your own choice.
		 *
		 * The preferred way to set values for initialization is:
		 *      CommRepository::MyCommObject obj;
		 *      obj.setX(1).setY(2).setZ(3)...;
		 */
		// CommDetectedTags(const std::vector<CommRobotinoObjects::CommVisualTag> &tags, const bool &valid = false);
		
		CommDetectedTags(const CommDetectedTagsCore &commDetectedTags);
		CommDetectedTags(const DATATYPE &commDetectedTags);
		virtual ~CommDetectedTags();
		
		// use framework specific getter and setter methods from core (base) class
		using CommDetectedTagsCore::get;
		using CommDetectedTagsCore::set;
		
		//
		// feel free to add customized methods here
		//

		bool getTagWithID(unsigned int id, CommRobotinoObjects::CommVisualTag& tag) const;
		bool setTagWithID(unsigned int id, const CommRobotinoObjects::CommVisualTag tag);

		inline CommBasicObjects::CommPose3d get_tag_pose_sensor(unsigned int i) const
		{
			return getTagsElemAtPos(i).getTagPose();
		}

		inline CommBasicObjects::CommPose3d get_tag_pose_robot(unsigned int i) const
		{

			CommRobotinoObjects::CommVisualTag tag = getTagsElemAtPos(i);
			arma::mat sensorPose = tag.getSensor_pose().getHomogeneousMatrix(1.0);
			arma::mat measurment = tag.getTagPose().getHomogeneousMatrix(1.0);

			arma::mat offset = sensorPose * measurment;
			return CommBasicObjects::CommPose3d(offset,1.0);

		}

		inline CommBasicObjects::CommPose3d get_tag_pose_world(unsigned int i) const
		{
			CommRobotinoObjects::CommVisualTag tag = getTagsElemAtPos(i);
			arma::mat sensorPose = tag.getSensor_pose().getHomogeneousMatrix(1.0);
			arma::mat robotPose = tag.getBase_state().getBasePose().getPose3D().getHomogeneousMatrix(1.0);
			arma::mat measurment = tag.getTagPose().getHomogeneousMatrix(1.0);

			arma::mat offset = robotPose * sensorPose * measurment;
			return CommBasicObjects::CommPose3d(offset,1.0);
		}
};

inline std::ostream &operator<<(std::ostream &os, const CommDetectedTags &co)
{
	co.to_ostream(os);
	return os;
}
	
} /* namespace CommRobotinoObjects */
#endif /* COMMROBOTINOOBJECTS_COMMDETECTEDTAGS_H_ */
