//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// This file is generated once. Modify this file to your needs. 
// If you want the toolchain to re-generate this file, please 
// delete it before running the code generator.
//--------------------------------------------------------------------------
#ifndef COMMROBOTINOOBJECTS_COMMPATHNAVIGATIONPOSEREQUESTEVENTPARAMETER_H_
#define COMMROBOTINOOBJECTS_COMMPATHNAVIGATIONPOSEREQUESTEVENTPARAMETER_H_

#include "CommRobotinoObjects/CommPathNavigationPoseRequestEventParameterCore.hh"

namespace CommRobotinoObjects {
		
class CommPathNavigationPoseRequestEventParameter : public CommPathNavigationPoseRequestEventParameterCore {
	public:
		// default constructors
		CommPathNavigationPoseRequestEventParameter();
		
		/**
		 * Constructor to set all values.
		 * NOTE that you have to keep this constructor consistent with the model!
		 * Use  at your own choice.
		 *
		 * The preferred way to set values for initialization is:
		 *      CommRepository::MyCommObject obj;
		 *      obj.setX(1).setY(2).setZ(3)...;
		 */
		// CommPathNavigationPoseRequestEventParameter(const CommRobotinoObjects::NodeRequestAnserType &oldState);
		
		CommPathNavigationPoseRequestEventParameter(const CommPathNavigationPoseRequestEventParameterCore &commPathNavigationPoseRequestEventParameter);
		CommPathNavigationPoseRequestEventParameter(const DATATYPE &commPathNavigationPoseRequestEventParameter);
		virtual ~CommPathNavigationPoseRequestEventParameter();
		
		// use framework specific getter and setter methods from core (base) class
		using CommPathNavigationPoseRequestEventParameterCore::get;
		using CommPathNavigationPoseRequestEventParameterCore::set;
		
		//
		// feel free to add customized methods here
		//
};

inline std::ostream &operator<<(std::ostream &os, const CommPathNavigationPoseRequestEventParameter &co)
{
	co.to_ostream(os);
	return os;
}
	
} /* namespace CommRobotinoObjects */
#endif /* COMMROBOTINOOBJECTS_COMMPATHNAVIGATIONPOSEREQUESTEVENTPARAMETER_H_ */
