//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// This file is generated once. Modify this file to your needs. 
// If you want the toolchain to re-generate this file, please 
// delete it before running the code generator.
//--------------------------------------------------------------------------

#include "CommRobotinoObjects/CommNavigationGraphEdge.hh"

using namespace CommRobotinoObjects;

CommNavigationGraphEdge::CommNavigationGraphEdge()
:	CommNavigationGraphEdgeCore()
{  }


/**
 * Constructor to set all values.
 * NOTE that you have to keep this constructor consistent with the model!
 * Use  at your own choice.
 *
 * The preferred way to set values for initialization is:
 *      CommRepository::MyCommObject obj;
 *      obj.setX(1).setY(2).setZ(3)...;
CommNavigationGraphEdge::CommNavigationGraphEdge(const int &u, const int &v, const int &path, const int &way, const double &gap, const CommRobotinoObjects::EDGE_TYPE &type)
:	CommNavigationGraphEdgeCore() // base constructor sets default values as defined in the model
{
	setU(u);
	setV(v);
	setPath(path);
	setWay(way);
	setGap(gap);
	setType(type);
}
 */

CommNavigationGraphEdge::CommNavigationGraphEdge(const CommNavigationGraphEdgeCore &commNavigationGraphEdge)
:	CommNavigationGraphEdgeCore(commNavigationGraphEdge)
{  }

CommNavigationGraphEdge::CommNavigationGraphEdge(const DATATYPE &commNavigationGraphEdge)
:	CommNavigationGraphEdgeCore(commNavigationGraphEdge)
{  }

CommNavigationGraphEdge::~CommNavigationGraphEdge()
{  }
