//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// This file is generated once. Modify this file to your needs. 
// If you want the toolchain to re-generate this file, please 
// delete it before running the code generator.
//--------------------------------------------------------------------------
// --------------------------------------------------------------------------
//
//  Copyright (C) 2013 Matthias Lutz
//
//        schlegel@hs-ulm.de
//
//        ZAFH Servicerobotik Ulm
//        University of Applied Sciences
//        Prittwitzstr. 10
//        D-89075 Ulm
//        Germany
//
//  This file is part of the "SmartSoft Communication Classes".
//  It provides basic standardized data types for communication between
//  different components in the mobile robotics context. These classes
//  are designed to be used in conjunction with the SmartSoft Communication
//  Library.
//
//  This library is free software; you can redistribute it and/or
//  modify it under the terms of the GNU Lesser General Public
//  License as published by the Free Software Foundation; either
//  version 2.1 of the License, or (at your option) any later version.
//
//  This library is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
//  Lesser General Public License for more details.
//
//  You should have received a copy of the GNU Lesser General Public
//  License along with this library; if not, write to the Free Software
//  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
//
// --------------------------------------------------------------------------


#include "CommRobotinoObjects/CommRobotinoConveyerBeltEventResult.hh"

#include <cstring>

using namespace CommRobotinoObjects;

CommRobotinoConveyerBeltEventResult::CommRobotinoConveyerBeltEventResult()
:	CommRobotinoConveyerBeltEventResultCore()
{  }


/**
 * Constructor to set all values.
 * NOTE that you have to keep this constructor consistent with the model!
 * Use  at your own choice.
 *
 * The preferred way to set values for initialization is:
 *      CommRepository::MyCommObject obj;
 *      obj.setX(1).setY(2).setZ(3)...;
CommRobotinoConveyerBeltEventResult::CommRobotinoConveyerBeltEventResult(const CommRobotinoObjects::RobotinoConveyerBeltEventType &state)
:	CommRobotinoConveyerBeltEventResultCore() // base constructor sets default values as defined in the model
{
	setState(state);
}
 */

void CommRobotinoConveyerBeltEventResult::set(RobotinoConveyerBeltEventType r)
{
	setState(r);
}

void CommRobotinoConveyerBeltEventResult::get(RobotinoConveyerBeltEventType& r) const
{
  r = getState();
}

void CommRobotinoConveyerBeltEventResult::get(char* r)const
{
  switch(idl_CommRobotinoConveyerBeltEventResult.state) {
    case RobotinoConveyerBeltEventType::CONVEYER_BELT_UNKNOWN:
      strcpy(r,"(unknown)");
      break;
    case RobotinoConveyerBeltEventType::CONVEYER_BELT_LOAD_DONE:
      strcpy(r,"(load done)");
      break;
    case RobotinoConveyerBeltEventType::CONVEYER_BELT_LOAD_NOT_DONE:
	  strcpy(r,"(load not done)");
	  break;
    case RobotinoConveyerBeltEventType::CONVEYER_BELT_UNLOAD_DONE:
      strcpy(r,"(unload done)");
      break;
    case RobotinoConveyerBeltEventType::CONVEYER_BELT_UNLOAD_NOT_DONE:
      strcpy(r,"(unload not done)");
      break;
    case RobotinoConveyerBeltEventType::CONVEYER_BELT_UNLOAD_ERROR_NO_BOX:
	  strcpy(r,"(unload error no box)");
	  break;
    case RobotinoConveyerBeltEventType::CONVEYER_BELT_UNLOAD_ERROR_BOX_STILL_PRESENT:
	  strcpy(r,"(unload error box still present)");
	  break;
    case RobotinoConveyerBeltEventType::CONVEYER_BELT_UNLOAD_ERROR_NO_RESPONSE_FROM_STATION:
	  strcpy(r,"(unload error no response from station)");
	  break;
    case RobotinoConveyerBeltEventType::CONVEYER_BELT_LOAD_ERROR_NO_BOX_LOADED:
	  strcpy(r,"(load error no box)");
	  break;
    case RobotinoConveyerBeltEventType::CONVEYER_BELT_LOAD_ERROR_BOX_ADREADY_PRSESENT:
	  strcpy(r,"(load error box already present)");
	  break;
    case RobotinoConveyerBeltEventType::CONVEYER_BELT_LOAD_ERROR_NO_RESPONSE_FROM_STATION:
	  strcpy(r,"(load error no response from station)");
	  break;
    default:
      strcpy(r,"(error)");
      break;
  }
}

void CommRobotinoConveyerBeltEventResult::print(std::ostream &os) const
{
  os << "Result : " << getState() << std::endl;
}


CommRobotinoConveyerBeltEventResult::CommRobotinoConveyerBeltEventResult(const CommRobotinoConveyerBeltEventResultCore &commRobotinoConveyerBeltEventResult)
:	CommRobotinoConveyerBeltEventResultCore(commRobotinoConveyerBeltEventResult)
{  }

CommRobotinoConveyerBeltEventResult::CommRobotinoConveyerBeltEventResult(const DATATYPE &commRobotinoConveyerBeltEventResult)
:	CommRobotinoConveyerBeltEventResultCore(commRobotinoConveyerBeltEventResult)
{  }

CommRobotinoConveyerBeltEventResult::~CommRobotinoConveyerBeltEventResult()
{  }
