#ifndef _MANIPULATIONPLANNERCOORDINATIONSERVICEPLANNEREVENTEVENTHANDLERCORE_HH_
#define _MANIPULATIONPLANNERCOORDINATIONSERVICEPLANNEREVENTEVENTHANDLERCORE_HH_
#include "aceSmartSoft.hh"
#include <string>

#include "CommManipulationPlannerObjects/CommManipulationPlannerEventResult.hh"
#include "CommManipulationPlannerObjects/CommManipulationPlannerEventParameter.hh"
#include "ManipulationPlannerCoordinationServicePlannereventEventHandler.hh"

class ManipulationPlannerCoordinationServicePlannereventEventHandlerCore : public Smart::IEventHandler<CommManipulationPlannerObjects::CommManipulationPlannerEventResult>
{
public:
	ManipulationPlannerCoordinationServicePlannereventEventHandlerCore(Smart::IEventClientPattern<CommManipulationPlannerObjects::CommManipulationPlannerEventParameter, CommManipulationPlannerObjects::CommManipulationPlannerEventResult> *client, std::string moduleInstanceName);
	virtual void handleEvent(const Smart::EventIdPtr &id, const CommManipulationPlannerObjects::CommManipulationPlannerEventResult &r) override;
	CommManipulationPlannerObjects::CommManipulationPlannerEventParameter activateEventParam(const std::string& parameterString);
private:
	ManipulationPlannerCoordinationServicePlannereventEventHandler userHandler;
	std::string ciInstanceName;
};

#endif
