//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef DOMAINSPEECH_COMMAMBIENTNOISE_ACE_H_
#define DOMAINSPEECH_COMMAMBIENTNOISE_ACE_H_

#include "DomainSpeech/CommAmbientNoise.hh"

#include <ace/CDR_Stream.h>

// serialization operator for DataStructure CommAmbientNoise
ACE_CDR::Boolean operator<<(ACE_OutputCDR &cdr, const DomainSpeechIDL::CommAmbientNoise &data);

// de-serialization operator for DataStructure CommAmbientNoise
ACE_CDR::Boolean operator>>(ACE_InputCDR &cdr, DomainSpeechIDL::CommAmbientNoise &data);

// serialization operator for CommunicationObject CommAmbientNoise
ACE_CDR::Boolean operator<<(ACE_OutputCDR &cdr, const DomainSpeech::CommAmbientNoise &obj);

// de-serialization operator for CommunicationObject CommAmbientNoise
ACE_CDR::Boolean operator>>(ACE_InputCDR &cdr, DomainSpeech::CommAmbientNoise &obj);

#endif /* DOMAINSPEECH_COMMAMBIENTNOISE_ACE_H_ */
