//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#include "DomainSpeech/CommSpeechInputEventResultACE.hh"
#include <ace/SString.h>

// serialization operator for element CommSpeechInputEventResult
ACE_CDR::Boolean operator<<(ACE_OutputCDR &cdr, const DomainSpeechIDL::CommSpeechInputEventResult &data)
{
	ACE_CDR::Boolean good_bit = true;
	// serialize list-element text
	good_bit = good_bit && cdr << ACE_CString(data.text.c_str());
	// serialize list-element confidence
	good_bit = good_bit && cdr.write_double(data.confidence);
	// serialize list-element semantic
	good_bit = good_bit && cdr << ACE_CString(data.semantic.c_str());
	
	return good_bit;
}

// de-serialization operator for element CommSpeechInputEventResult
ACE_CDR::Boolean operator>>(ACE_InputCDR &cdr, DomainSpeechIDL::CommSpeechInputEventResult &data)
{
	ACE_CDR::Boolean good_bit = true;
	// deserialize string-type element text
	ACE_CString data_text_str;
	good_bit = good_bit && cdr >> data_text_str;
	data.text = data_text_str.c_str();
	// deserialize type element confidence
	good_bit = good_bit && cdr.read_double(data.confidence);
	// deserialize string-type element semantic
	ACE_CString data_semantic_str;
	good_bit = good_bit && cdr >> data_semantic_str;
	data.semantic = data_semantic_str.c_str();
	
	return good_bit;
}

// serialization operator for CommunicationObject CommSpeechInputEventResult
ACE_CDR::Boolean operator<<(ACE_OutputCDR &cdr, const DomainSpeech::CommSpeechInputEventResult &obj)
{
	return cdr << obj.get();
}

// de-serialization operator for CommunicationObject CommSpeechInputEventResult
ACE_CDR::Boolean operator>>(ACE_InputCDR &cdr, DomainSpeech::CommSpeechInputEventResult &obj)
{
	return cdr >> obj.set();
}
