//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef COMMROBOTINOOBJECTS_COMMROBOTINOCONVEYERBELTEVENTRESULT_CORE_H_
#define COMMROBOTINOOBJECTS_COMMROBOTINOCONVEYERBELTEVENTRESULT_CORE_H_

#include "CommRobotinoObjects/CommRobotinoConveyerBeltEventResultData.hh"
#include "CommRobotinoObjects/enumRobotinoConveyerBeltEventType.hh"

#include <iostream>
#include <string>
#include <list>

namespace CommRobotinoObjects {
	
class CommRobotinoConveyerBeltEventResultCore {
protected:
	// data structure
	CommRobotinoObjectsIDL::CommRobotinoConveyerBeltEventResult idl_CommRobotinoConveyerBeltEventResult;
	
public:
	// give a publicly accessible type-name for the template parameter IDL
	typedef CommRobotinoObjectsIDL::CommRobotinoConveyerBeltEventResult DATATYPE;
	
	#ifdef ENABLE_HASH
		static size_t generateDataHash(const DATATYPE &);
	#endif
	
	static const char* getCompiledHash();
	static void getAllHashValues(std::list<std::string> &hashes);
	static void checkAllHashValues(std::list<std::string> &hashes);
	
	// default constructors
	CommRobotinoConveyerBeltEventResultCore();
	CommRobotinoConveyerBeltEventResultCore(const DATATYPE &data);
	// default destructor
	virtual ~CommRobotinoConveyerBeltEventResultCore();
	
	const DATATYPE& get() const { return idl_CommRobotinoConveyerBeltEventResult; }
	operator const DATATYPE&() const { return idl_CommRobotinoConveyerBeltEventResult; }
	DATATYPE& set() { return idl_CommRobotinoConveyerBeltEventResult; }

	static inline std::string identifier(void) { return "CommRobotinoObjects::CommRobotinoConveyerBeltEventResult"; }
	
	// helper method to easily implement output stream in derived classes
	void to_ostream(std::ostream &os = std::cout) const;
	
	// convert to xml stream
	void to_xml(std::ostream &os, const std::string &indent = "") const;
	
	// restore from xml stream
	void from_xml(std::istream &is);
	
	// User Interface
	
	// getter and setter for element State
	inline CommRobotinoObjects::RobotinoConveyerBeltEventType getState() const { return CommRobotinoObjects::RobotinoConveyerBeltEventType(idl_CommRobotinoConveyerBeltEventResult.state); }
	inline CommRobotinoConveyerBeltEventResultCore& setState(const CommRobotinoObjects::RobotinoConveyerBeltEventType &state) { idl_CommRobotinoConveyerBeltEventResult.state = state; return *this; }
};

} /* namespace CommRobotinoObjects */
#endif /* COMMROBOTINOOBJECTS_COMMROBOTINOCONVEYERBELTEVENTRESULT_CORE_H_ */
