//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef COMMROBOTINOOBJECTS_COMMCOORDINATEDNAVIGATIONRESOURCEREQUEST_DATA_H_
#define COMMROBOTINOOBJECTS_COMMCOORDINATEDNAVIGATIONRESOURCEREQUEST_DATA_H_

#include "CommRobotinoObjects/enumCoordinatedNavigationResourceRequestActionTypeData.hh"


namespace CommRobotinoObjectsIDL 
{
	struct CommCoordinatedNavigationResourceRequest
	{
		int resourceID;
		int robotID;
		CommRobotinoObjectsIDL::CoordinatedNavigationResourceRequestActionType actionType;
  	};
};

#endif /* COMMROBOTINOOBJECTS_COMMCOORDINATEDNAVIGATIONRESOURCEREQUEST_DATA_H_ */
