//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef COMMROBOTINOOBJECTS_COMMPATHFREEAREA_DATA_H_
#define COMMROBOTINOOBJECTS_COMMPATHFREEAREA_DATA_H_


#include <vector>

namespace CommRobotinoObjectsIDL 
{
	typedef std::vector<int> CommPathFreeArea_robotIDs_type;
	typedef std::vector<double> CommPathFreeArea_nodeXvector_type;
	typedef std::vector<double> CommPathFreeArea_nodeYvector_type;
	struct CommPathFreeArea
	{
		int areaID;
		int maxOccupancy;
		CommPathFreeArea_robotIDs_type robotIDs;
		CommPathFreeArea_nodeXvector_type nodeXvector;
		CommPathFreeArea_nodeYvector_type nodeYvector;
  	};
};

#endif /* COMMROBOTINOOBJECTS_COMMPATHFREEAREA_DATA_H_ */
