//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef COMMROBOTINOOBJECTS_COMMPATHNAVIGATIONPOSEREQUEST_CORE_H_
#define COMMROBOTINOOBJECTS_COMMPATHNAVIGATIONPOSEREQUEST_CORE_H_

#include "CommRobotinoObjects/CommPathNavigationPoseRequestData.hh"
#include "CommRobotinoObjects/enumNavigationNodeRequestType.hh"

#include <iostream>
#include <string>
#include <list>

namespace CommRobotinoObjects {
	
class CommPathNavigationPoseRequestCore {
protected:
	// data structure
	CommRobotinoObjectsIDL::CommPathNavigationPoseRequest idl_CommPathNavigationPoseRequest;
	
public:
	// give a publicly accessible type-name for the template parameter IDL
	typedef CommRobotinoObjectsIDL::CommPathNavigationPoseRequest DATATYPE;
	
	#ifdef ENABLE_HASH
		static size_t generateDataHash(const DATATYPE &);
	#endif
	
	static const char* getCompiledHash();
	static void getAllHashValues(std::list<std::string> &hashes);
	static void checkAllHashValues(std::list<std::string> &hashes);
	
	// default constructors
	CommPathNavigationPoseRequestCore();
	CommPathNavigationPoseRequestCore(const DATATYPE &data);
	// default destructor
	virtual ~CommPathNavigationPoseRequestCore();
	
	const DATATYPE& get() const { return idl_CommPathNavigationPoseRequest; }
	operator const DATATYPE&() const { return idl_CommPathNavigationPoseRequest; }
	DATATYPE& set() { return idl_CommPathNavigationPoseRequest; }

	static inline std::string identifier(void) { return "CommRobotinoObjects::CommPathNavigationPoseRequest"; }
	
	// helper method to easily implement output stream in derived classes
	void to_ostream(std::ostream &os = std::cout) const;
	
	// convert to xml stream
	void to_xml(std::ostream &os, const std::string &indent = "") const;
	
	// restore from xml stream
	void from_xml(std::istream &is);
	
	// User Interface
	
	// getter and setter for element Requesttype
	inline CommRobotinoObjects::NavigationNodeRequestType getRequesttype() const { return CommRobotinoObjects::NavigationNodeRequestType(idl_CommPathNavigationPoseRequest.requesttype); }
	inline CommPathNavigationPoseRequestCore& setRequesttype(const CommRobotinoObjects::NavigationNodeRequestType &requesttype) { idl_CommPathNavigationPoseRequest.requesttype = requesttype; return *this; }
	
	// getter and setter for element Pose
	inline unsigned int getPose() const { return idl_CommPathNavigationPoseRequest.pose; }
	inline CommPathNavigationPoseRequestCore& setPose(const unsigned int &pose) { idl_CommPathNavigationPoseRequest.pose = pose; return *this; }
	
	// getter and setter for element RobotID
	inline std::string getRobotID() const { return idl_CommPathNavigationPoseRequest.robotID; }
	inline CommPathNavigationPoseRequestCore& setRobotID(const std::string &robotID) { idl_CommPathNavigationPoseRequest.robotID = robotID; return *this; }
};

} /* namespace CommRobotinoObjects */
#endif /* COMMROBOTINOOBJECTS_COMMPATHNAVIGATIONPOSEREQUEST_CORE_H_ */
