//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef COMMROBOTINOOBJECTS_COMMPATHNAVIGATIONPOSEREQUESTEVENTSTATE_DATA_H_
#define COMMROBOTINOOBJECTS_COMMPATHNAVIGATIONPOSEREQUESTEVENTSTATE_DATA_H_

#include "CommRobotinoObjects/enumNodeRequestAnserTypeData.hh"


namespace CommRobotinoObjectsIDL 
{
	struct CommPathNavigationPoseRequestEventState
	{
		CommRobotinoObjectsIDL::NodeRequestAnserType newState;
  	};
};

#endif /* COMMROBOTINOOBJECTS_COMMPATHNAVIGATIONPOSEREQUESTEVENTSTATE_DATA_H_ */
