//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#include "CommRobotinoObjects/CommLicenseKeyACE.hh"
#include <ace/SString.h>
#include "CommBasicObjects/CommTimeStampACE.hh"

// serialization operator for element CommLicenseKey
ACE_CDR::Boolean operator<<(ACE_OutputCDR &cdr, const CommRobotinoObjectsIDL::CommLicenseKey &data)
{
	ACE_CDR::Boolean good_bit = true;
	// serialize list-element key
	good_bit = good_bit && cdr << ACE_CString(data.key.c_str());
	// serialize list-element valid
	good_bit = good_bit && cdr.write_boolean(data.valid);
	// serialize list-element timestamp
	good_bit = good_bit && cdr << data.timestamp;
	
	return good_bit;
}

// de-serialization operator for element CommLicenseKey
ACE_CDR::Boolean operator>>(ACE_InputCDR &cdr, CommRobotinoObjectsIDL::CommLicenseKey &data)
{
	ACE_CDR::Boolean good_bit = true;
	// deserialize string-type element key
	ACE_CString data_key_str;
	good_bit = good_bit && cdr >> data_key_str;
	data.key = data_key_str.c_str();
	// deserialize type element valid
	good_bit = good_bit && cdr.read_boolean(data.valid);
	// deserialize type element timestamp
	good_bit = good_bit && cdr >> data.timestamp;
	
	return good_bit;
}

// serialization operator for CommunicationObject CommLicenseKey
ACE_CDR::Boolean operator<<(ACE_OutputCDR &cdr, const CommRobotinoObjects::CommLicenseKey &obj)
{
	return cdr << obj.get();
}

// de-serialization operator for CommunicationObject CommLicenseKey
ACE_CDR::Boolean operator>>(ACE_InputCDR &cdr, CommRobotinoObjects::CommLicenseKey &obj)
{
	return cdr >> obj.set();
}
