//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef COMMROBOTINOOBJECTS_COMMPATHNETWORKSTATUS_DATA_H_
#define COMMROBOTINOOBJECTS_COMMPATHNETWORKSTATUS_DATA_H_

#include "CommRobotinoObjects/CommPathNodeData.hh"

#include <vector>

namespace CommRobotinoObjectsIDL 
{
	typedef std::vector<CommRobotinoObjectsIDL::CommPathNode> CommPathNetworkStatus_nodes_type;
	struct CommPathNetworkStatus
	{
		CommPathNetworkStatus_nodes_type nodes;
  	};
};

#endif /* COMMROBOTINOOBJECTS_COMMPATHNETWORKSTATUS_DATA_H_ */
