//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef COMMROBOTINOOBJECTS_COMMCLOSESTNODEANSWER_CORE_H_
#define COMMROBOTINOOBJECTS_COMMCLOSESTNODEANSWER_CORE_H_

#include "CommRobotinoObjects/CommClosestNodeAnswerData.hh"
#include "CommBasicObjects/CommPosition3d.hh"

#include <iostream>
#include <string>
#include <list>

namespace CommRobotinoObjects {
	
class CommClosestNodeAnswerCore {
protected:
	// data structure
	CommRobotinoObjectsIDL::CommClosestNodeAnswer idl_CommClosestNodeAnswer;
	
public:
	// give a publicly accessible type-name for the template parameter IDL
	typedef CommRobotinoObjectsIDL::CommClosestNodeAnswer DATATYPE;
	
	#ifdef ENABLE_HASH
		static size_t generateDataHash(const DATATYPE &);
	#endif
	
	static const char* getCompiledHash();
	static void getAllHashValues(std::list<std::string> &hashes);
	static void checkAllHashValues(std::list<std::string> &hashes);
	
	// default constructors
	CommClosestNodeAnswerCore();
	CommClosestNodeAnswerCore(const DATATYPE &data);
	// default destructor
	virtual ~CommClosestNodeAnswerCore();
	
	const DATATYPE& get() const { return idl_CommClosestNodeAnswer; }
	operator const DATATYPE&() const { return idl_CommClosestNodeAnswer; }
	DATATYPE& set() { return idl_CommClosestNodeAnswer; }

	static inline std::string identifier(void) { return "CommRobotinoObjects::CommClosestNodeAnswer"; }
	
	// helper method to easily implement output stream in derived classes
	void to_ostream(std::ostream &os = std::cout) const;
	
	// convert to xml stream
	void to_xml(std::ostream &os, const std::string &indent = "") const;
	
	// restore from xml stream
	void from_xml(std::istream &is);
	
	// User Interface
	
	// getter and setter for element Node_id
	inline int getNode_id() const { return idl_CommClosestNodeAnswer.node_id; }
	inline CommClosestNodeAnswerCore& setNode_id(const int &node_id) { idl_CommClosestNodeAnswer.node_id = node_id; return *this; }
	
	// getter and setter for element Position
	inline CommBasicObjects::CommPosition3d getPosition() const { return CommBasicObjects::CommPosition3d(idl_CommClosestNodeAnswer.position); }
	inline CommClosestNodeAnswerCore& setPosition(const CommBasicObjects::CommPosition3d &position) { idl_CommClosestNodeAnswer.position = position; return *this; }
	
	// getter and setter for element Distance
	inline double getDistance() const { return idl_CommClosestNodeAnswer.distance; }
	inline CommClosestNodeAnswerCore& setDistance(const double &distance) { idl_CommClosestNodeAnswer.distance = distance; return *this; }
	
	// getter and setter for element Valid
	inline bool getValid() const { return idl_CommClosestNodeAnswer.valid; }
	inline CommClosestNodeAnswerCore& setValid(const bool &valid) { idl_CommClosestNodeAnswer.valid = valid; return *this; }
};

} /* namespace CommRobotinoObjects */
#endif /* COMMROBOTINOOBJECTS_COMMCLOSESTNODEANSWER_CORE_H_ */
