//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef COMMROBOTINOOBJECTS_COMMPATHNODE_DATA_H_
#define COMMROBOTINOOBJECTS_COMMPATHNODE_DATA_H_

#include "CommRobotinoObjects/enumNODE_STATUSData.hh"
#include "CommRobotinoObjects/enumNODE_TYPEData.hh"

#include <string>

namespace CommRobotinoObjectsIDL 
{
	struct CommPathNode
	{
		unsigned int id;
		double x;
		double y;
		unsigned int pose;
		unsigned int path;
		double width;
		CommRobotinoObjectsIDL::NODE_TYPE type;
		CommRobotinoObjectsIDL::NODE_STATUS sts;
		std::string robotID;
  	};
};

#endif /* COMMROBOTINOOBJECTS_COMMPATHNODE_DATA_H_ */
