//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef COMMROBOTINOOBJECTS_COMMNAVIGATIONGRAPH_CORE_H_
#define COMMROBOTINOOBJECTS_COMMNAVIGATIONGRAPH_CORE_H_

#include "CommRobotinoObjects/CommNavigationGraphData.hh"
#include "CommRobotinoObjects/CommNavigationGraphVertex.hh"
#include "CommRobotinoObjects/CommNavigationGraphEdge.hh"

#include <iostream>
#include <string>
#include <list>

namespace CommRobotinoObjects {
	
class CommNavigationGraphCore {
protected:
	// data structure
	CommRobotinoObjectsIDL::CommNavigationGraph idl_CommNavigationGraph;
	
public:
	// give a publicly accessible type-name for the template parameter IDL
	typedef CommRobotinoObjectsIDL::CommNavigationGraph DATATYPE;
	
	#ifdef ENABLE_HASH
		static size_t generateDataHash(const DATATYPE &);
	#endif
	
	static const char* getCompiledHash();
	static void getAllHashValues(std::list<std::string> &hashes);
	static void checkAllHashValues(std::list<std::string> &hashes);
	
	// default constructors
	CommNavigationGraphCore();
	CommNavigationGraphCore(const DATATYPE &data);
	// default destructor
	virtual ~CommNavigationGraphCore();
	
	const DATATYPE& get() const { return idl_CommNavigationGraph; }
	operator const DATATYPE&() const { return idl_CommNavigationGraph; }
	DATATYPE& set() { return idl_CommNavigationGraph; }

	static inline std::string identifier(void) { return "CommRobotinoObjects::CommNavigationGraph"; }
	
	// helper method to easily implement output stream in derived classes
	void to_ostream(std::ostream &os = std::cout) const;
	
	// convert to xml stream
	void to_xml(std::ostream &os, const std::string &indent = "") const;
	
	// restore from xml stream
	void from_xml(std::istream &is);
	
	// User Interface
	
	// getter and setter for element Vertices
	/**
	 * Getter methods for element idl_CommNavigationGraph.vertices of type vector<CommRobotinoObjects::CommNavigationGraphVertex>
	 */
	inline std::vector<CommRobotinoObjects::CommNavigationGraphVertex> getVerticesCopy() const { 
		return std::vector<CommRobotinoObjects::CommNavigationGraphVertex>(idl_CommNavigationGraph.vertices.begin(), idl_CommNavigationGraph.vertices.end());
	}
	inline CommRobotinoObjects::CommNavigationGraphVertex getVerticesElemAtPos(const size_t &pos) const {
		return CommRobotinoObjects::CommNavigationGraphVertex(idl_CommNavigationGraph.vertices[pos]);
	}
	inline size_t getVerticesSize() const { return idl_CommNavigationGraph.vertices.size(); }
	inline bool isVerticesEmpty() const { return idl_CommNavigationGraph.vertices.empty(); }
	/**
	 * Setter methods for idl_CommNavigationGraph.vertices of type vector<CommRobotinoObjects::CommNavigationGraphVertex>
	 */
	inline CommNavigationGraphCore& setVertices(const std::vector<CommRobotinoObjects::CommNavigationGraphVertex> &vertices) { 
		idl_CommNavigationGraph.vertices.assign(vertices.begin(), vertices.end());
		return *this;
	}
	inline bool setVerticesElemAtPos(const size_t &pos, const CommRobotinoObjects::CommNavigationGraphVertex &elem) {
		if(pos < idl_CommNavigationGraph.vertices.size()) {
			idl_CommNavigationGraph.vertices[pos] = elem;
			return true;
		}
		return false;
	}
	inline bool insertVerticesVectorAtPos(const size_t &pos, const std::vector<CommRobotinoObjects::CommNavigationGraphVertex> &data) {
		if(pos < idl_CommNavigationGraph.vertices.size()) {
			idl_CommNavigationGraph.vertices.insert(idl_CommNavigationGraph.vertices.begin()+pos, data.begin(), data.end());
			return true;
		}
		return false;
	}
	inline void resizeVertices(const size_t &size) { idl_CommNavigationGraph.vertices.resize(size); }
	inline bool eraseVerticesElemsAtPos(const size_t &pos, const size_t &nbr_elems) {
		if( (pos+nbr_elems) <= idl_CommNavigationGraph.vertices.size() ) {
			idl_CommNavigationGraph.vertices.erase(idl_CommNavigationGraph.vertices.begin()+pos, idl_CommNavigationGraph.vertices.begin()+pos+nbr_elems);
			return true;
		}
		return false;
	}
	inline void clearVertices() { idl_CommNavigationGraph.vertices.clear(); }
	
	// getter and setter for element Edges
	/**
	 * Getter methods for element idl_CommNavigationGraph.edges of type vector<CommRobotinoObjects::CommNavigationGraphEdge>
	 */
	inline std::vector<CommRobotinoObjects::CommNavigationGraphEdge> getEdgesCopy() const { 
		return std::vector<CommRobotinoObjects::CommNavigationGraphEdge>(idl_CommNavigationGraph.edges.begin(), idl_CommNavigationGraph.edges.end());
	}
	inline CommRobotinoObjects::CommNavigationGraphEdge getEdgesElemAtPos(const size_t &pos) const {
		return CommRobotinoObjects::CommNavigationGraphEdge(idl_CommNavigationGraph.edges[pos]);
	}
	inline size_t getEdgesSize() const { return idl_CommNavigationGraph.edges.size(); }
	inline bool isEdgesEmpty() const { return idl_CommNavigationGraph.edges.empty(); }
	/**
	 * Setter methods for idl_CommNavigationGraph.edges of type vector<CommRobotinoObjects::CommNavigationGraphEdge>
	 */
	inline CommNavigationGraphCore& setEdges(const std::vector<CommRobotinoObjects::CommNavigationGraphEdge> &edges) { 
		idl_CommNavigationGraph.edges.assign(edges.begin(), edges.end());
		return *this;
	}
	inline bool setEdgesElemAtPos(const size_t &pos, const CommRobotinoObjects::CommNavigationGraphEdge &elem) {
		if(pos < idl_CommNavigationGraph.edges.size()) {
			idl_CommNavigationGraph.edges[pos] = elem;
			return true;
		}
		return false;
	}
	inline bool insertEdgesVectorAtPos(const size_t &pos, const std::vector<CommRobotinoObjects::CommNavigationGraphEdge> &data) {
		if(pos < idl_CommNavigationGraph.edges.size()) {
			idl_CommNavigationGraph.edges.insert(idl_CommNavigationGraph.edges.begin()+pos, data.begin(), data.end());
			return true;
		}
		return false;
	}
	inline void resizeEdges(const size_t &size) { idl_CommNavigationGraph.edges.resize(size); }
	inline bool eraseEdgesElemsAtPos(const size_t &pos, const size_t &nbr_elems) {
		if( (pos+nbr_elems) <= idl_CommNavigationGraph.edges.size() ) {
			idl_CommNavigationGraph.edges.erase(idl_CommNavigationGraph.edges.begin()+pos, idl_CommNavigationGraph.edges.begin()+pos+nbr_elems);
			return true;
		}
		return false;
	}
	inline void clearEdges() { idl_CommNavigationGraph.edges.clear(); }
	
	// getter and setter for element PathWidth
	/**
	 * Getter methods for idl_CommNavigationGraph.pathWidth of type vector<double>
	 */
	inline std::vector<double>& getPathWidthRef() { return idl_CommNavigationGraph.pathWidth; }
	inline std::vector<double> getPathWidthCopy() const {
		return std::vector<double>(idl_CommNavigationGraph.pathWidth.begin(), idl_CommNavigationGraph.pathWidth.end());
	}
	inline double getPathWidthElemAtPos(const size_t &pos) const { return idl_CommNavigationGraph.pathWidth[pos]; }
	inline size_t getPathWidthSize() const { return idl_CommNavigationGraph.pathWidth.size(); }
	inline bool isPathWidthEmpty() const { return idl_CommNavigationGraph.pathWidth.empty(); }
	/**
	 * Setter methods for idl_CommNavigationGraph.pathWidth of type vector<double>
	 */
	inline CommNavigationGraphCore& setPathWidth(const std::vector<double> &pathWidth) { idl_CommNavigationGraph.pathWidth = pathWidth; return *this; }
	inline bool setPathWidthElemAtPos(const size_t &pos, const double &elem) {
		if(pos < idl_CommNavigationGraph.pathWidth.size()) {
			idl_CommNavigationGraph.pathWidth[pos] = elem;
			return true;
		}
		return false;
	}
	inline bool insertPathWidthVectorAtPos(const size_t &pos, const std::vector<double> &data) {
		if(pos < idl_CommNavigationGraph.pathWidth.size()) {
			idl_CommNavigationGraph.pathWidth.insert(idl_CommNavigationGraph.pathWidth.begin()+pos, data.begin(), data.end());
			return true;
		}
		return false;
	}
	inline void resizePathWidth(const size_t &size) { idl_CommNavigationGraph.pathWidth.resize(size); }
	inline bool erasePathWidthElemsAtPos(const size_t &pos, const size_t &nbr_elems) {
		if( (pos+nbr_elems) <= idl_CommNavigationGraph.pathWidth.size() ) {
			idl_CommNavigationGraph.pathWidth.erase(idl_CommNavigationGraph.pathWidth.begin()+pos, idl_CommNavigationGraph.pathWidth.begin()+pos+nbr_elems);
			return true;
		}
		return false;
	}
	inline void clearPathWidth() { idl_CommNavigationGraph.pathWidth.clear(); }
	
	// getter and setter for element Valid
	inline bool getValid() const { return idl_CommNavigationGraph.valid; }
	inline CommNavigationGraphCore& setValid(const bool &valid) { idl_CommNavigationGraph.valid = valid; return *this; }
};

} /* namespace CommRobotinoObjects */
#endif /* COMMROBOTINOOBJECTS_COMMNAVIGATIONGRAPH_CORE_H_ */
