//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#include "CommRobotinoObjects/CommCoordinatedNavigationDataRequestACE.hh"
#include <ace/SString.h>

// serialization operator for element CommCoordinatedNavigationDataRequest
ACE_CDR::Boolean operator<<(ACE_OutputCDR &cdr, const CommRobotinoObjectsIDL::CommCoordinatedNavigationDataRequest &data)
{
	ACE_CDR::Boolean good_bit = true;
	// serialize list-element resourceID
	good_bit = good_bit && cdr.write_long(data.resourceID);
	
	return good_bit;
}

// de-serialization operator for element CommCoordinatedNavigationDataRequest
ACE_CDR::Boolean operator>>(ACE_InputCDR &cdr, CommRobotinoObjectsIDL::CommCoordinatedNavigationDataRequest &data)
{
	ACE_CDR::Boolean good_bit = true;
	// deserialize type element resourceID
	good_bit = good_bit && cdr.read_long(data.resourceID);
	
	return good_bit;
}

// serialization operator for CommunicationObject CommCoordinatedNavigationDataRequest
ACE_CDR::Boolean operator<<(ACE_OutputCDR &cdr, const CommRobotinoObjects::CommCoordinatedNavigationDataRequest &obj)
{
	return cdr << obj.get();
}

// de-serialization operator for CommunicationObject CommCoordinatedNavigationDataRequest
ACE_CDR::Boolean operator>>(ACE_InputCDR &cdr, CommRobotinoObjects::CommCoordinatedNavigationDataRequest &obj)
{
	return cdr >> obj.set();
}
