//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef COMMROBOTINOOBJECTS_COMMPATHNAVIGATIONNODEPATHREQUEST_CORE_H_
#define COMMROBOTINOOBJECTS_COMMPATHNAVIGATIONNODEPATHREQUEST_CORE_H_

#include "CommRobotinoObjects/CommPathNavigationNodePathRequestData.hh"

#include <iostream>
#include <string>
#include <list>

namespace CommRobotinoObjects {
	
class CommPathNavigationNodePathRequestCore {
protected:
	// data structure
	CommRobotinoObjectsIDL::CommPathNavigationNodePathRequest idl_CommPathNavigationNodePathRequest;
	
public:
	// give a publicly accessible type-name for the template parameter IDL
	typedef CommRobotinoObjectsIDL::CommPathNavigationNodePathRequest DATATYPE;
	
	#ifdef ENABLE_HASH
		static size_t generateDataHash(const DATATYPE &);
	#endif
	
	static const char* getCompiledHash();
	static void getAllHashValues(std::list<std::string> &hashes);
	static void checkAllHashValues(std::list<std::string> &hashes);
	
	// default constructors
	CommPathNavigationNodePathRequestCore();
	CommPathNavigationNodePathRequestCore(const DATATYPE &data);
	// default destructor
	virtual ~CommPathNavigationNodePathRequestCore();
	
	const DATATYPE& get() const { return idl_CommPathNavigationNodePathRequest; }
	operator const DATATYPE&() const { return idl_CommPathNavigationNodePathRequest; }
	DATATYPE& set() { return idl_CommPathNavigationNodePathRequest; }

	static inline std::string identifier(void) { return "CommRobotinoObjects::CommPathNavigationNodePathRequest"; }
	
	// helper method to easily implement output stream in derived classes
	void to_ostream(std::ostream &os = std::cout) const;
	
	// convert to xml stream
	void to_xml(std::ostream &os, const std::string &indent = "") const;
	
	// restore from xml stream
	void from_xml(std::istream &is);
	
	// User Interface
	
	// getter and setter for element StartPose
	inline unsigned int getStartPose() const { return idl_CommPathNavigationNodePathRequest.startPose; }
	inline CommPathNavigationNodePathRequestCore& setStartPose(const unsigned int &startPose) { idl_CommPathNavigationNodePathRequest.startPose = startPose; return *this; }
	
	// getter and setter for element GoalPose
	inline unsigned int getGoalPose() const { return idl_CommPathNavigationNodePathRequest.goalPose; }
	inline CommPathNavigationNodePathRequestCore& setGoalPose(const unsigned int &goalPose) { idl_CommPathNavigationNodePathRequest.goalPose = goalPose; return *this; }
};

} /* namespace CommRobotinoObjects */
#endif /* COMMROBOTINOOBJECTS_COMMPATHNAVIGATIONNODEPATHREQUEST_CORE_H_ */
