//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef COMMROBOTINOOBJECTS_COMMROBOTINODOCKINGEVENTRESULT_ACE_H_
#define COMMROBOTINOOBJECTS_COMMROBOTINODOCKINGEVENTRESULT_ACE_H_

#include "CommRobotinoObjects/CommRobotinoDockingEventResult.hh"

#include <ace/CDR_Stream.h>

// serialization operator for DataStructure CommRobotinoDockingEventResult
ACE_CDR::Boolean operator<<(ACE_OutputCDR &cdr, const CommRobotinoObjectsIDL::CommRobotinoDockingEventResult &data);

// de-serialization operator for DataStructure CommRobotinoDockingEventResult
ACE_CDR::Boolean operator>>(ACE_InputCDR &cdr, CommRobotinoObjectsIDL::CommRobotinoDockingEventResult &data);

// serialization operator for CommunicationObject CommRobotinoDockingEventResult
ACE_CDR::Boolean operator<<(ACE_OutputCDR &cdr, const CommRobotinoObjects::CommRobotinoDockingEventResult &obj);

// de-serialization operator for CommunicationObject CommRobotinoDockingEventResult
ACE_CDR::Boolean operator>>(ACE_InputCDR &cdr, CommRobotinoObjects::CommRobotinoDockingEventResult &obj);

#endif /* COMMROBOTINOOBJECTS_COMMROBOTINODOCKINGEVENTRESULT_ACE_H_ */
