//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#include "DomainPTU/CommPTUGoalEventResultACE.hh"
#include <ace/SString.h>
#include "DomainPTU/enumPTUMoveStatusData.hh"

// serialization operator for element CommPTUGoalEventResult
ACE_CDR::Boolean operator<<(ACE_OutputCDR &cdr, const DomainPTUIDL::CommPTUGoalEventResult &data)
{
	ACE_CDR::Boolean good_bit = true;
	// serialize list-element state
	good_bit = good_bit && cdr.write_long(data.state);
	
	return good_bit;
}

// de-serialization operator for element CommPTUGoalEventResult
ACE_CDR::Boolean operator>>(ACE_InputCDR &cdr, DomainPTUIDL::CommPTUGoalEventResult &data)
{
	ACE_CDR::Boolean good_bit = true;
	// deserialize type element state
	good_bit = good_bit && cdr.read_long(data.state);
	
	return good_bit;
}

// serialization operator for CommunicationObject CommPTUGoalEventResult
ACE_CDR::Boolean operator<<(ACE_OutputCDR &cdr, const DomainPTU::CommPTUGoalEventResult &obj)
{
	return cdr << obj.get();
}

// de-serialization operator for CommunicationObject CommPTUGoalEventResult
ACE_CDR::Boolean operator>>(ACE_InputCDR &cdr, DomainPTU::CommPTUGoalEventResult &obj)
{
	return cdr >> obj.set();
}
