//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#include "CommBasicObjects/CommKBResponseACE.hh"
#include <ace/SString.h>

// serialization operator for element CommKBResponse
ACE_CDR::Boolean operator<<(ACE_OutputCDR &cdr, const CommBasicObjectsIDL::CommKBResponse &data)
{
	ACE_CDR::Boolean good_bit = true;
	// serialize list-element response
	good_bit = good_bit && cdr << ACE_CString(data.response.c_str());
	
	return good_bit;
}

// de-serialization operator for element CommKBResponse
ACE_CDR::Boolean operator>>(ACE_InputCDR &cdr, CommBasicObjectsIDL::CommKBResponse &data)
{
	ACE_CDR::Boolean good_bit = true;
	// deserialize string-type element response
	ACE_CString data_response_str;
	good_bit = good_bit && cdr >> data_response_str;
	data.response = data_response_str.c_str();
	
	return good_bit;
}

// serialization operator for CommunicationObject CommKBResponse
ACE_CDR::Boolean operator<<(ACE_OutputCDR &cdr, const CommBasicObjects::CommKBResponse &obj)
{
	return cdr << obj.get();
}

// de-serialization operator for CommunicationObject CommKBResponse
ACE_CDR::Boolean operator>>(ACE_InputCDR &cdr, CommBasicObjects::CommKBResponse &obj)
{
	return cdr >> obj.set();
}
