//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef COMMMANIPULATOROBJECTS_COMMMANIPULATORID_DATA_H_
#define COMMMANIPULATOROBJECTS_COMMMANIPULATORID_DATA_H_



namespace CommManipulatorObjectsIDL 
{
	struct CommManipulatorId
	{
		unsigned int id;
		bool valid;
  	};
};

#endif /* COMMMANIPULATOROBJECTS_COMMMANIPULATORID_DATA_H_ */
