//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef COMMMANIPULATOROBJECTS_COMMGRIPPEREVENT_CORE_H_
#define COMMMANIPULATOROBJECTS_COMMGRIPPEREVENT_CORE_H_

#include "CommManipulatorObjects/CommGripperEventData.hh"
#include "CommManipulatorObjects/enumGripperEvent.hh"

#include <iostream>
#include <string>
#include <list>

namespace CommManipulatorObjects {
	
class CommGripperEventCore {
protected:
	// data structure
	CommManipulatorObjectsIDL::CommGripperEvent idl_CommGripperEvent;
	
public:
	// give a publicly accessible type-name for the template parameter IDL
	typedef CommManipulatorObjectsIDL::CommGripperEvent DATATYPE;
	
	#ifdef ENABLE_HASH
		static size_t generateDataHash(const DATATYPE &);
	#endif
	
	static const char* getCompiledHash();
	static void getAllHashValues(std::list<std::string> &hashes);
	static void checkAllHashValues(std::list<std::string> &hashes);
	
	// default constructors
	CommGripperEventCore();
	CommGripperEventCore(const DATATYPE &data);
	// default destructor
	virtual ~CommGripperEventCore();
	
	const DATATYPE& get() const { return idl_CommGripperEvent; }
	operator const DATATYPE&() const { return idl_CommGripperEvent; }
	DATATYPE& set() { return idl_CommGripperEvent; }

	static inline std::string identifier(void) { return "CommManipulatorObjects::CommGripperEvent"; }
	
	// helper method to easily implement output stream in derived classes
	void to_ostream(std::ostream &os = std::cout) const;
	
	// convert to xml stream
	void to_xml(std::ostream &os, const std::string &indent = "") const;
	
	// restore from xml stream
	void from_xml(std::istream &is);
	
	// User Interface
	
	// getter and setter for element Gripper_event
	inline CommManipulatorObjects::GripperEvent getGripper_event() const { return CommManipulatorObjects::GripperEvent(idl_CommGripperEvent.gripper_event); }
	inline CommGripperEventCore& setGripper_event(const CommManipulatorObjects::GripperEvent &gripper_event) { idl_CommGripperEvent.gripper_event = gripper_event; return *this; }
	
	// getter and setter for element Pos
	inline float getPos() const { return idl_CommGripperEvent.pos; }
	inline CommGripperEventCore& setPos(const float &pos) { idl_CommGripperEvent.pos = pos; return *this; }
};

} /* namespace CommManipulatorObjects */
#endif /* COMMMANIPULATOROBJECTS_COMMGRIPPEREVENT_CORE_H_ */
