//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef COMMMANIPULATOROBJECTS_MANIPULATOREVENT_ENUM_H_
#define COMMMANIPULATOROBJECTS_MANIPULATOREVENT_ENUM_H_

#include <CommManipulatorObjects/enumManipulatorEventData.hh>

#include <string>
#include <iostream>

// SmartUtils used in from_xml method
#include "smartKnuthMorrisPratt.hh"

namespace CommManipulatorObjects {
	
	class ManipulatorEvent {
	private:
		CommManipulatorObjectsIDL::ManipulatorEvent value;
		
	public:
		enum ENUM_ManipulatorEvent {
			ENUM_VALUE_UNDEFINED = 0,
			COLLISION = 1,
			NO_SOLUTION_FOUND = 2,
			VALUE_OUT_OF_RANGE = 3,
			GOAL_REACHED = 4,
			GOAL_NOT_REACHED = 5,
			UNKNOWN = 6
		};
		
		// default constructor
		ManipulatorEvent() { 
			value = ENUM_VALUE_UNDEFINED;
		}
		
		// copy constructor for enum type
		ManipulatorEvent(ENUM_ManipulatorEvent e) {
			value = static_cast<int>(e);
		}
		
		// copy constructor for IDL type
		ManipulatorEvent(CommManipulatorObjectsIDL::ManipulatorEvent e) {
			value = e;
		}
		
		//const CommManipulatorObjectsIDL::ManipulatorEvent& get() const { return value; }
		
		// ENUM operator
		operator ENUM_ManipulatorEvent() const {
			return static_cast<ENUM_ManipulatorEvent>(value);
		}
		
		// compare operator
		bool operator == (const ENUM_ManipulatorEvent t) const {
			return this->value == t;
		}
		
		std::string to_string() const {
			std::string result = "";
			switch (value) {
				case COLLISION:
					result = "ManipulatorEvent::COLLISION";
					break;
				case NO_SOLUTION_FOUND:
					result = "ManipulatorEvent::NO_SOLUTION_FOUND";
					break;
				case VALUE_OUT_OF_RANGE:
					result = "ManipulatorEvent::VALUE_OUT_OF_RANGE";
					break;
				case GOAL_REACHED:
					result = "ManipulatorEvent::GOAL_REACHED";
					break;
				case GOAL_NOT_REACHED:
					result = "ManipulatorEvent::GOAL_NOT_REACHED";
					break;
				case UNKNOWN:
					result = "ManipulatorEvent::UNKNOWN";
					break;
				default:
					result = "ENUM_VALUE_UNDEFINED";
					break;
			};
			return result;
		}
		
		// helper method to easily implement output stream
		void to_ostream(std::ostream &os = std::cout) const {
			os << to_string();
		}
		
		// convert to xml stream
		void to_xml(std::ostream &os, const std::string &indent = "") const {
			os << indent << "<value>" << value << "</value>";
		}
		
		// restore from xml stream
		void from_xml(std::istream &is) {
			static const Smart::KnuthMorrisPratt kmp_value("<value>");
			if(kmp_value.search(is)) {
				is >> value;
			}
		}
	
	};
	
	inline std::ostream &operator<<(std::ostream &os, const ManipulatorEvent &e)
	{
		e.to_ostream(os);
		return os;
	}
};

#endif
