//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// This file is generated once. Modify this file to your needs. 
// If you want the toolchain to re-generate this file, please 
// delete it before running the code generator.
//--------------------------------------------------------------------------
#ifndef COMMTRACKINGOBJECTS_LEADEREVENTSTATE_H_
#define COMMTRACKINGOBJECTS_LEADEREVENTSTATE_H_

#include "CommTrackingObjects/LeaderEventStateCore.hh"

namespace CommTrackingObjects {
		
class LeaderEventState : public LeaderEventStateCore {
	public:
		// default constructors
		LeaderEventState();
		
		/**
		 * Constructor to set all values.
		 * NOTE that you have to keep this constructor consistent with the model!
		 * Use  at your own choice.
		 *
		 * The preferred way to set values for initialization is:
		 *      CommRepository::MyCommObject obj;
		 *      obj.setX(1).setY(2).setZ(3)...;
		 */
		// LeaderEventState(const CommTrackingObjects::LeaderEventType &type, const int &goal_x, const int &goal_y);
		
		LeaderEventState(const LeaderEventStateCore &leaderEventState);
		LeaderEventState(const DATATYPE &leaderEventState);
		virtual ~LeaderEventState();
		
		// use framework specific getter and setter methods from core (base) class
		using LeaderEventStateCore::get;
		using LeaderEventStateCore::set;
		
		//
		// feel free to add customized methods here
		//
};

inline std::ostream &operator<<(std::ostream &os, const LeaderEventState &co)
{
	co.to_ostream(os);
	return os;
}
	
} /* namespace CommTrackingObjects */
#endif /* COMMTRACKINGOBJECTS_LEADEREVENTSTATE_H_ */
